-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- sco_desenv.dbo.ISC_I01_VERSAO_BANCO_DADOS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.ISC_I01_VERSAO_BANCO_DADOS;

CREATE TABLE sco_desenv.dbo.ISC_I01_VERSAO_BANCO_DADOS (
	I01_NR_MAJOR_VERSION tinyint NOT NULL,
	I01_NR_MINOR_VERSION tinyint NOT NULL,
	I01_NR_REVISION int NOT NULL,
	CONSTRAINT I01_I1_VERSAO_BANCO_DADOS PRIMARY KEY (I01_NR_MAJOR_VERSION,I01_NR_MINOR_VERSION,I01_NR_REVISION)
);


-- sco_desenv.dbo.SCO_C00_VERSAO_BANCO_DADOS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C00_VERSAO_BANCO_DADOS;

CREATE TABLE sco_desenv.dbo.SCO_C00_VERSAO_BANCO_DADOS (
	C00_NR_MAJOR_VERSION smallint NOT NULL,
	C00_NR_MINOR_VERSION smallint NOT NULL,
	C00_NR_REVISION smallint NOT NULL,
	CONSTRAINT P00_I1_VERSAO_BANCO_DADOS PRIMARY KEY (C00_NR_MAJOR_VERSION,C00_NR_MINOR_VERSION,C00_NR_REVISION)
);


-- sco_desenv.dbo.SCO_C01_PARAMETROS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C01_PARAMETROS;

CREATE TABLE sco_desenv.dbo.SCO_C01_PARAMETROS (
	C01_ID_PARAMETRO tinyint NOT NULL,
	C01_TX_DESCRICAO varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C01_VL_PARAMETRO varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C01_TP_PARAMETRO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C01_TM_TIME_STAMP datetime NOT NULL,
	C01_TX_USER_STAMP varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C01_IN_PERMITE_BRANCO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT P01_I1_PARAMETROS PRIMARY KEY (C01_ID_PARAMETRO)
);


-- sco_desenv.dbo.SCO_C02_TIPOS_TEAR definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C02_TIPOS_TEAR;

CREATE TABLE sco_desenv.dbo.SCO_C02_TIPOS_TEAR (
	C02_ID_TIPO_TEAR int IDENTITY(1,1) NOT NULL,
	C02_TX_MODELO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C02_DT_INCLUSAO datetime NULL,
	C02_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C02_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C02_I1_TIPOS_TEAR PRIMARY KEY (C02_ID_TIPO_TEAR)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C02_I2_TIPOS_TEAR ON dbo.SCO_C02_TIPOS_TEAR (  C02_TX_MODELO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C03_TIPOS_PROGRAMA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C03_TIPOS_PROGRAMA;

CREATE TABLE sco_desenv.dbo.SCO_C03_TIPOS_PROGRAMA (
	C03_ID_TIPO_PROGRAMA int IDENTITY(1,1) NOT NULL,
	C03_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C03_DT_INCLUSAO datetime NOT NULL,
	C03_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C03_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C03_I1_TIPOS_PROGRAMA PRIMARY KEY (C03_ID_TIPO_PROGRAMA)
);


-- sco_desenv.dbo.SCO_C04_TIPOS_APARELHO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C04_TIPOS_APARELHO;

CREATE TABLE sco_desenv.dbo.SCO_C04_TIPOS_APARELHO (
	C04_ID_TIPO_APARELHO tinyint IDENTITY(1,1) NOT NULL,
	C04_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C04_DT_INCLUSAO datetime NOT NULL,
	C04_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C04_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C04_I1_TIPOS_APARELHO PRIMARY KEY (C04_ID_TIPO_APARELHO)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C04_I2_TIPOS_APARELHO ON dbo.SCO_C04_TIPOS_APARELHO (  C04_TX_DESCRICAO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C05_FAMILIA_PRODUTO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C05_FAMILIA_PRODUTO;

CREATE TABLE sco_desenv.dbo.SCO_C05_FAMILIA_PRODUTO (
	C05_ID_FAMILIA_PRODUTO smallint IDENTITY(1,1) NOT NULL,
	C05_CD_FAMILIA_PRODUTO varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C05_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C05_NR_PERCENTUAL_PERDA decimal(5,2) NULL,
	C05_NR_PESO_MAXIMO_PECA_GRAMAS decimal(10,2) NULL,
	C05_DT_INCLUSAO datetime NOT NULL,
	C05_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C05_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C05_I1_FAMILIAS_PRODUTO PRIMARY KEY (C05_ID_FAMILIA_PRODUTO)
);
 CREATE  UNIQUE CLUSTERED INDEX C05_I2_FAMILIAS_PRODUTO ON dbo.SCO_C05_FAMILIA_PRODUTO (  C05_CD_FAMILIA_PRODUTO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C08_TIPOS_TENSAO_KTF definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C08_TIPOS_TENSAO_KTF;

CREATE TABLE sco_desenv.dbo.SCO_C08_TIPOS_TENSAO_KTF (
	C08_ID_TIPO_TENSAO_KTF tinyint NOT NULL,
	C08_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C08_I1_TIPO_TENSAO_KTF PRIMARY KEY (C08_ID_TIPO_TENSAO_KTF)
);


-- sco_desenv.dbo.SCO_C09_CORREDORES definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C09_CORREDORES;

CREATE TABLE sco_desenv.dbo.SCO_C09_CORREDORES (
	C09_ID_CORREDOR smallint IDENTITY(1,1) NOT NULL,
	C09_NR_CORREDOR char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C09_DT_INCLUSAO datetime NOT NULL,
	C09_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C09_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C09_I1_CORREDORES PRIMARY KEY (C09_ID_CORREDOR)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C09_I2_CORREDORES ON dbo.SCO_C09_CORREDORES (  C09_NR_CORREDOR ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C10_TURNOS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C10_TURNOS;

CREATE TABLE sco_desenv.dbo.SCO_C10_TURNOS (
	C10_ID_TURNO smallint IDENTITY(1,1) NOT NULL,
	C10_TX_DESCRICAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C10_NR_HORA_INICIO smallint NOT NULL,
	C10_NR_MINUTO_INICIO smallint NOT NULL,
	C10_NR_HORA_FIM smallint NOT NULL,
	C10_NR_MINUTO_FIM smallint NOT NULL,
	C10_DT_INCLUSAO datetime NULL,
	C10_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C10_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C10_I1_TURNOS PRIMARY KEY (C10_ID_TURNO)
);


-- sco_desenv.dbo.SCO_C11_LADOS_CORREDOR definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C11_LADOS_CORREDOR;

CREATE TABLE sco_desenv.dbo.SCO_C11_LADOS_CORREDOR (
	C11_ID_LADO_CORREDOR smallint NOT NULL,
	C11_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C11_I1_LADOS_CORREDOR PRIMARY KEY (C11_ID_LADO_CORREDOR)
);


-- sco_desenv.dbo.SCO_C12_FLUXOS_FABRICACAO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C12_FLUXOS_FABRICACAO;

CREATE TABLE sco_desenv.dbo.SCO_C12_FLUXOS_FABRICACAO (
	C12_ID_FLUXO_FABRICACAO tinyint NOT NULL,
	C12_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C12_I1_FLUXOS_FABRICACOES PRIMARY KEY (C12_ID_FLUXO_FABRICACAO)
);


-- sco_desenv.dbo.SCO_C13_MOTIVOS_PARADA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C13_MOTIVOS_PARADA;

CREATE TABLE sco_desenv.dbo.SCO_C13_MOTIVOS_PARADA (
	C13_ID_MOTIVO_PARADA smallint IDENTITY(1,1) NOT NULL,
	C13_TX_DESCRICAO varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C13_DT_INCLUSAO datetime NOT NULL,
	C13_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C13_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C13_I1_MOTIVO_PARADAS PRIMARY KEY (C13_ID_MOTIVO_PARADA)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C13_I2_MOTIVO_PARADAS ON dbo.SCO_C13_MOTIVOS_PARADA (  C13_TX_DESCRICAO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C14_TIPOS_REFUGO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C14_TIPOS_REFUGO;

CREATE TABLE sco_desenv.dbo.SCO_C14_TIPOS_REFUGO (
	C14_ID_TIPO_REFUGO tinyint IDENTITY(1,1) NOT NULL,
	C14_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C14_ST_OBRIGATORIO tinyint NOT NULL,
	C14_DT_INCLUSAO datetime NULL,
	C14_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C14_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C14_I1_TIPOS_REFUGO PRIMARY KEY (C14_ID_TIPO_REFUGO)
);
 CREATE  UNIQUE CLUSTERED INDEX C14_I2_TIPOS_REFUGO ON dbo.SCO_C14_TIPOS_REFUGO (  C14_TX_DESCRICAO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C15_TIPOS_MONTAGEM_CODIGO_INTERNO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C15_TIPOS_MONTAGEM_CODIGO_INTERNO;

CREATE TABLE sco_desenv.dbo.SCO_C15_TIPOS_MONTAGEM_CODIGO_INTERNO (
	C15_ID_TIPO_MONTAGEM_CODIGO_INTERNO tinyint NOT NULL,
	C15_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C15_TX_COMPLEMENTO_FIXO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C15_ST_PARTE_FIXA tinyint NOT NULL,
	C15_ST_PARTE_INFORMADA tinyint NOT NULL,
	CONSTRAINT C15_I1_TIPO_MONTAGEM_CODIGO_INTERNO PRIMARY KEY (C15_ID_TIPO_MONTAGEM_CODIGO_INTERNO)
);


-- sco_desenv.dbo.SCO_C16_MEDIDAS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C16_MEDIDAS;

CREATE TABLE sco_desenv.dbo.SCO_C16_MEDIDAS (
	C16_ID_MEDIDA tinyint IDENTITY(1,1) NOT NULL,
	C16_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C16_NR_ORDEM_FICHA tinyint NOT NULL,
	C16_DT_INCLUSAO datetime NULL,
	C16_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C16_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C16_I1_MEDIDAS PRIMARY KEY (C16_ID_MEDIDA)
);
 CREATE  UNIQUE CLUSTERED INDEX C16_I2_MEDIDAS ON dbo.SCO_C16_MEDIDAS (  C16_TX_DESCRICAO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C17_FORMATOS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C17_FORMATOS;

CREATE TABLE sco_desenv.dbo.SCO_C17_FORMATOS (
	C17_ID_FORMATO tinyint NOT NULL,
	C17_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C17_I1_FORMATOS PRIMARY KEY (C17_ID_FORMATO)
);


-- sco_desenv.dbo.SCO_C18_TIPOS_PRODUTO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C18_TIPOS_PRODUTO;

CREATE TABLE sco_desenv.dbo.SCO_C18_TIPOS_PRODUTO (
	C18_ID_TIPO_PRODUTO smallint NOT NULL,
	C18_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C18_I1_TIPOS_PRODUTO PRIMARY KEY (C18_ID_TIPO_PRODUTO)
);


-- sco_desenv.dbo.SCO_C19_STATUS_FICHA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C19_STATUS_FICHA;

CREATE TABLE sco_desenv.dbo.SCO_C19_STATUS_FICHA (
	C19_ID_STATUS_FICHA int NOT NULL,
	C19_TX_DESCRICAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C36_ID_EVENTO int NULL,
	CONSTRAINT C19_I1_STATUS_FICHA PRIMARY KEY (C19_ID_STATUS_FICHA)
);


-- sco_desenv.dbo.SCO_C20_FICHAS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C20_FICHAS;

CREATE TABLE sco_desenv.dbo.SCO_C20_FICHAS (
	C20_ID_FICHA int IDENTITY(1,1) NOT NULL,
	C20_NR_VERSAO int NULL,
	C20_CD_PRODUTO char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C18_ID_TIPO_PRODUTO smallint NOT NULL,
	C19_ID_STATUS_FICHA tinyint NOT NULL,
	C20_DT_REVISAO datetime NULL,
	C20_DT_VERSAO datetime NULL,
	C20_TX_JUSTIFICATIVA varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C20_CD_USUARIO_ELABORACAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C20_TX_OBSERVACAO varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C20_DT_INCLUSAO datetime NULL,
	C20_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C20_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C20_ID_FICHA_ORIGEM_COPIA int NULL,
	C20_SG_VERSAO char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C20_I1_FICHAS PRIMARY KEY (C20_ID_FICHA)
);


-- sco_desenv.dbo.SCO_C29_APROVACAO_FICHA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C29_APROVACAO_FICHA;

CREATE TABLE sco_desenv.dbo.SCO_C29_APROVACAO_FICHA (
	C29_ID_APROVACAO_FICHA int IDENTITY(1,1) NOT NULL,
	C20_ID_FICHA int NOT NULL,
	C29_NR_SEQUENCIA_APROVACAO int NOT NULL,
	C29_NR_ORDEM_APROVACAO int NOT NULL,
	S02_CD_PERFIL char(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C29_DT_APROVACAO datetime NULL,
	C29_ST_APROVACAO tinyint NULL,
	S02_CD_USUARIO_APROVACAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C29_TX_JUSTIFICATIVA varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT C29_I1_APROVACAO_FICHA PRIMARY KEY (C29_ID_APROVACAO_FICHA)
);


-- sco_desenv.dbo.SCO_C30_SEMANAS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C30_SEMANAS;

CREATE TABLE sco_desenv.dbo.SCO_C30_SEMANAS (
	C30_CD_SEMANA int NOT NULL,
	C30_DT_INICIO smalldatetime NOT NULL,
	C30_DT_FIM smalldatetime NOT NULL,
	C30_NR_DIAS tinyint NOT NULL,
	S02_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C30_DT_INCLUSAO datetime NOT NULL,
	C30_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C30_I1_SEMANAS PRIMARY KEY (C30_CD_SEMANA)
);


-- sco_desenv.dbo.SCO_C33_PROGRAMACAO_TEARES definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C33_PROGRAMACAO_TEARES;

CREATE TABLE sco_desenv.dbo.SCO_C33_PROGRAMACAO_TEARES (
	C33_ID_PROGRAMACAO_TEARES int IDENTITY(1,1) NOT NULL,
	C32_ID_PRODUTO_PLANO_PRODUCAO int NOT NULL,
	C33_NR_SEQUENCIAL_TEAR int NOT NULL,
	C06_ID_TEAR int NULL,
	C33_NR_META_PECAS int NOT NULL,
	C33_NR_ORDEM_TROCA int NULL,
	C33_DT_TROCA datetime NULL,
	C33_DT_INCLUSAO datetime NULL,
	C33_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C33_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C33_I1_PROGRAMACAO_TEARES PRIMARY KEY (C33_ID_PROGRAMACAO_TEARES)
);


-- sco_desenv.dbo.SCO_C34_TIPOS_LOTE definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C34_TIPOS_LOTE;

CREATE TABLE sco_desenv.dbo.SCO_C34_TIPOS_LOTE (
	C34_ID_TIPO_LOTE tinyint NOT NULL,
	C34_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C34_I1_TIPOS_LOTE PRIMARY KEY (C34_ID_TIPO_LOTE)
);


-- sco_desenv.dbo.SCO_C35_DESCARTE definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C35_DESCARTE;

CREATE TABLE sco_desenv.dbo.SCO_C35_DESCARTE (
	C35_ID_DESCARTE tinyint NOT NULL,
	C35_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C35_I1_DESCARTE PRIMARY KEY (C35_ID_DESCARTE)
);


-- sco_desenv.dbo.SCO_C36_EVENTOS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C36_EVENTOS;

CREATE TABLE sco_desenv.dbo.SCO_C36_EVENTOS (
	C36_ID_EVENTO int NOT NULL,
	C36_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C36_I1_EVENTO PRIMARY KEY (C36_ID_EVENTO)
);


-- sco_desenv.dbo.SCO_C37_TIPOS_OF definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C37_TIPOS_OF;

CREATE TABLE sco_desenv.dbo.SCO_C37_TIPOS_OF (
	C37_ID_TIPO_OF tinyint NOT NULL,
	C37_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C37_ST_AVULSA tinyint NOT NULL,
	CONSTRAINT C37_I1_TIPOS_OF PRIMARY KEY (C37_ID_TIPO_OF)
);


-- sco_desenv.dbo.SCO_C38_STATUS_LOTE definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C38_STATUS_LOTE;

CREATE TABLE sco_desenv.dbo.SCO_C38_STATUS_LOTE (
	C38_ID_STATUS_LOTE tinyint NOT NULL,
	C38_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C38_I1_STATUS_LOTE PRIMARY KEY (C38_ID_STATUS_LOTE)
);


-- sco_desenv.dbo.SCO_C39_STATUS_OF definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C39_STATUS_OF;

CREATE TABLE sco_desenv.dbo.SCO_C39_STATUS_OF (
	C39_ID_STATUS_OF tinyint NOT NULL,
	C39_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C39_I1_STATUS_OF PRIMARY KEY (C39_ID_STATUS_OF)
);


-- sco_desenv.dbo.SCO_C45_TROCA_LOTE_INSUMO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C45_TROCA_LOTE_INSUMO;

CREATE TABLE sco_desenv.dbo.SCO_C45_TROCA_LOTE_INSUMO (
	C45_ID_TROCA_LOTE_INSUMO int IDENTITY(1,1) NOT NULL,
	L03_CD_MATERIAL char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	A14_NR_LOTE char(7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C45_DT_INCLUSAO datetime NULL,
	C45_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C45_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C45_I1_TROCA_LOTE_INSUMO PRIMARY KEY (C45_ID_TROCA_LOTE_INSUMO)
);


-- sco_desenv.dbo.SCO_C46_LOTES_ARTIGO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C46_LOTES_ARTIGO;

CREATE TABLE sco_desenv.dbo.SCO_C46_LOTES_ARTIGO (
	C46_ID_LOTE_ARTIGO int IDENTITY(1,1) NOT NULL,
	C45_ID_TROCA_LOTE_INSUMO int NOT NULL,
	C46_NR_LOTE_ARTIGO int NOT NULL,
	C46_DT_INCLUSAO datetime NULL,
	C46_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C46_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C46_I1_LOTES_ARTIGO PRIMARY KEY (C46_ID_LOTE_ARTIGO)
);


-- sco_desenv.dbo.SCO_C47_LOTES_INSUMO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C47_LOTES_INSUMO;

CREATE TABLE sco_desenv.dbo.SCO_C47_LOTES_INSUMO (
	C47_ID_LOTE_INSUMO int IDENTITY(1,1) NOT NULL,
	C46_ID_LOTE_ARTIGO int NOT NULL,
	L03_CD_MATERIAL char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	A14_NR_LOTE char(7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C47_DT_INCLUSAO datetime NULL,
	C47_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C47_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C45_I1_LOTES_INSUMO PRIMARY KEY (C47_ID_LOTE_INSUMO)
);


-- sco_desenv.dbo.SCO_C48_TIPOS_LANCAMENTO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C48_TIPOS_LANCAMENTO;

CREATE TABLE sco_desenv.dbo.SCO_C48_TIPOS_LANCAMENTO (
	C48_ID_TIPO_LANCAMENTO tinyint NOT NULL,
	C48_TX_DESCRICAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C48_ST_ENTRADA tinyint NULL,
	CONSTRAINT S48_I1_TIPOS_LANCAMENTO PRIMARY KEY (C48_ID_TIPO_LANCAMENTO)
);


-- sco_desenv.dbo.SCO_C49_TIPOS_MOVIMENTACAO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C49_TIPOS_MOVIMENTACAO;

CREATE TABLE sco_desenv.dbo.SCO_C49_TIPOS_MOVIMENTACAO (
	C49_ID_TIPO_MOVIMENTACAO tinyint NOT NULL,
	C49_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C48_ID_TIPO_LANCAMENTO tinyint NOT NULL,
	C49_TX_HISTORICO varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C49_TX_OBSERVACAO varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT C49_I1_TIPOS_MOVIMENTACAO PRIMARY KEY (C49_ID_TIPO_MOVIMENTACAO)
);


-- sco_desenv.dbo.SCO_C50_ESTOQUE_INSUMO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C50_ESTOQUE_INSUMO;

CREATE TABLE sco_desenv.dbo.SCO_C50_ESTOQUE_INSUMO (
	C50_ID_ESTOQUE_INSUMO int IDENTITY(1,1) NOT NULL,
	L03_CD_MATERIAL char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	L11_CD_MESTRE char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C50_NR_QUANTIDADE smallmoney NOT NULL,
	C50_NR_QUANTIDADE_PULMAO smallmoney NOT NULL,
	C50_DT_INCLUSAO datetime NULL,
	C50_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C50_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C50_I1_ESTOQUE_INSUMO PRIMARY KEY (C50_ID_ESTOQUE_INSUMO)
);


-- sco_desenv.dbo.SCO_C51_MOVIMENTACAO_ESTOQUE_INSUMO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C51_MOVIMENTACAO_ESTOQUE_INSUMO;

CREATE TABLE sco_desenv.dbo.SCO_C51_MOVIMENTACAO_ESTOQUE_INSUMO (
	C51_ID_MOVIMENTACAO_ESTOQUE_INSUMO int IDENTITY(1,1) NOT NULL,
	C50_ID_ESTOQUE_INSUMO int NOT NULL,
	C49_ID_TIPO_MOVIMENTACAO tinyint NOT NULL,
	C49_DT_MOVIMENTACAO datetime NOT NULL,
	C51_NR_QUANTIDADE smallmoney NOT NULL,
	C51_ID_LANCAMENTO int NOT NULL,
	C51_TX_OBSERVACAO varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C51_ST_GERADO_SISTEMA tinyint NULL,
	C51_DT_INCLUSAO datetime NULL,
	C51_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C51_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C51_I1_MOVIMENTACAO_ESTOQUE_INSUMO PRIMARY KEY (C51_ID_MOVIMENTACAO_ESTOQUE_INSUMO)
);


-- sco_desenv.dbo.SCO_C52_REQUISICAO_INSUMO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C52_REQUISICAO_INSUMO;

CREATE TABLE sco_desenv.dbo.SCO_C52_REQUISICAO_INSUMO (
	C52_ID_REQUISICAO_INSUMO int IDENTITY(1,1) NOT NULL,
	L03_CD_MATERIAL char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	M15_TX_DESCRICAO char(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	A15_ID_ESTOQUE int NOT NULL,
	A14_ID_ROMANEIO int NOT NULL,
	A02_ID_ALMOX_PROCES int NOT NULL,
	A04_ID_LOCAL int NOT NULL,
	A04_CD_LOCAL char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	A04_TX_DESCRICAO varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	A15_NR_CAIXA smallint NOT NULL,
	A15_NR_PESO_BRUTO smallmoney NOT NULL,
	A15_NR_PESO_LIQUIDO smallmoney NOT NULL,
	A15_NR_TARA smallmoney NOT NULL,
	A15_NR_QTDE int NOT NULL,
	A19_ST_PECA char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	A15_NR_NUM_PECA char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	A14_NR_ROMANEIO int NOT NULL,
	A12_ID_EMBALAGEM int NOT NULL,
	A12_TX_DESCRICAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	A14_DT_ENTRADA smalldatetime NOT NULL,
	A14_NR_LOTE char(7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	A14_TX_OBSERVACOES varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	A18_ID_MOVIMENTACAO int NULL,
	C52_DT_INCLUSAO datetime NOT NULL,
	C52_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C52_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C52_DT_CONFIRMACAO_RECEBIMENTO datetime NOT NULL,
	C52_CD_USUARIO_CONFIRMACAO_RECEBIMENTO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C52_ID_REQUISICAO_INSUMO PRIMARY KEY (C52_ID_REQUISICAO_INSUMO)
);


-- sco_desenv.dbo.SCO_C67_EVENTOS_NATUREZA_DOCUMENTOS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C67_EVENTOS_NATUREZA_DOCUMENTOS;

CREATE TABLE sco_desenv.dbo.SCO_C67_EVENTOS_NATUREZA_DOCUMENTOS (
	C37_ID_TIPO_OF tinyint NOT NULL,
	C36_ID_EVENTO int NOT NULL,
	C67_CD_NATUREZA tinyint NOT NULL,
	C67_CD_CENTRO_CUSTO_ATENDE char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C67_NR_CONTA_ATENDE char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C67_CD_CENTRO_CUSTO_RECEBE char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C67_NR_CONTA_RECEBE char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
);
 CREATE  UNIQUE CLUSTERED INDEX C37_I1_EVENTOS_NATUREZA_DOCUMENTOS ON dbo.SCO_C67_EVENTOS_NATUREZA_DOCUMENTOS (  C37_ID_TIPO_OF ASC  , C36_ID_EVENTO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C69_STATUS_ROMANEIO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C69_STATUS_ROMANEIO;

CREATE TABLE sco_desenv.dbo.SCO_C69_STATUS_ROMANEIO (
	C69_ID_STATUS_ROMANEIO tinyint NOT NULL,
	C69_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C69_I1_STATUS_ROMANEIO PRIMARY KEY (C69_ID_STATUS_ROMANEIO)
);


-- sco_desenv.dbo.SCO_C70_ROMANEIO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C70_ROMANEIO;

CREATE TABLE sco_desenv.dbo.SCO_C70_ROMANEIO (
	C70_ID_ROMANEIO int IDENTITY(1,1) NOT NULL,
	C70_NR_TOTAL_PESO_GRAMAS decimal(20,2) NULL,
	C69_ID_STATUS_ROMANEIO tinyint NOT NULL,
	C70_DT_EMISSAO datetime NULL,
	C70_DT_INCLUSAO datetime NULL,
	C70_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C70_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C70_I1_ROMANEIO PRIMARY KEY (C70_ID_ROMANEIO)
);


-- sco_desenv.dbo.SCO_C71_CAIXAS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C71_CAIXAS;

CREATE TABLE sco_desenv.dbo.SCO_C71_CAIXAS (
	C71_ID_CAIXA int IDENTITY(1,1) NOT NULL,
	C70_ID_ROMANEIO int NOT NULL,
	C71_NR_CAIXA int NOT NULL,
	C71_DT_INCLUSAO datetime NULL,
	C71_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C71_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C71_I1_CAIXAS PRIMARY KEY (C71_ID_CAIXA)
);


-- sco_desenv.dbo.SCO_C73_SUBTIPOS_REFUGO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C73_SUBTIPOS_REFUGO;

CREATE TABLE sco_desenv.dbo.SCO_C73_SUBTIPOS_REFUGO (
	C73_ID_SUBTIPO_REFUGO tinyint IDENTITY(1,1) NOT NULL,
	C14_ID_TIPO_REFUGO tinyint NOT NULL,
	C73_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C73_DT_INCLUSAO datetime NULL,
	C73_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C73_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C73_I1_TIPOS_REFUGO PRIMARY KEY (C73_ID_SUBTIPO_REFUGO)
);


-- sco_desenv.dbo.SCO_C74_STATUS_REFUGO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C74_STATUS_REFUGO;

CREATE TABLE sco_desenv.dbo.SCO_C74_STATUS_REFUGO (
	C74_ID_STATUS_REFUGO tinyint NOT NULL,
	C74_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C74_I1_STATUS_REFUGO PRIMARY KEY (C74_ID_STATUS_REFUGO)
);


-- sco_desenv.dbo.SCO_C75_REFUGOS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C75_REFUGOS;

CREATE TABLE sco_desenv.dbo.SCO_C75_REFUGOS (
	C75_ID_REFUGO int IDENTITY(1,1) NOT NULL,
	C45_NR_OF int NOT NULL,
	C14_ID_TIPO_REFUGO tinyint NOT NULL,
	C10_ID_TURNO smallint NOT NULL,
	C75_NR_CODIGO_BARRAS int NULL,
	C75_DT_RECOLHIMENTO datetime NULL,
	P01_CD_EMPREGADO int NULL,
	C74_ID_STATUS_REFUGO tinyint NOT NULL,
	C75_DT_INCLUSAO datetime NULL,
	C75_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C75_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C75_I1_REFUGOS PRIMARY KEY (C75_ID_REFUGO)
);


-- sco_desenv.dbo.SCO_C76_STATUS_ROMANEIO_CONTROLE_AMBIENTAL definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C76_STATUS_ROMANEIO_CONTROLE_AMBIENTAL;

CREATE TABLE sco_desenv.dbo.SCO_C76_STATUS_ROMANEIO_CONTROLE_AMBIENTAL (
	C76_ID_STATUS_ROMANEIO_CONTROLE_AMBIENTAL tinyint NOT NULL,
	C76_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C76_I1_STATUS_ROMANEIO_CONTROLE_AMBIENTAL PRIMARY KEY (C76_ID_STATUS_ROMANEIO_CONTROLE_AMBIENTAL)
);


-- sco_desenv.dbo.SCO_C77_ROMANEIO_CONTROLE_AMBIENTAL definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C77_ROMANEIO_CONTROLE_AMBIENTAL;

CREATE TABLE sco_desenv.dbo.SCO_C77_ROMANEIO_CONTROLE_AMBIENTAL (
	C77_ID_ROMANEIO_CONTROLE_AMBIENTAL int IDENTITY(1,1) NOT NULL,
	C76_ID_STATUS_ROMANEIO_CONTROLE_AMBIENTAL tinyint NOT NULL,
	C77_NR_TOTAL_PESO_GRAMAS decimal(20,2) NULL,
	C77_DT_EMISSAO datetime NULL,
	C77_DT_ENVIO datetime NULL,
	C77_DT_INCLUSAO datetime NULL,
	C77_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C77_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C77_I1_PESAGEM_REFUGO PRIMARY KEY (C77_ID_ROMANEIO_CONTROLE_AMBIENTAL)
);


-- sco_desenv.dbo.SCO_C78_REFUGO_ROMANEIO_CONTROLE_AMBIENTAL definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C78_REFUGO_ROMANEIO_CONTROLE_AMBIENTAL;

CREATE TABLE sco_desenv.dbo.SCO_C78_REFUGO_ROMANEIO_CONTROLE_AMBIENTAL (
	SCO_C78_REFUGO_ROMANEIO_CONTROLE_AMBIENTAL int IDENTITY(1,1) NOT NULL,
	C77_ID_ROMANEIO_CONTROLE_AMBIENTAL int NOT NULL,
	C75_ID_REFUGO int NOT NULL,
	C73_ID_SUBTIPO_REFUGO tinyint NULL,
	C78_NR_PESO_GRAMAS decimal(10,2) NULL,
	C78_DT_INCLUSAO datetime NULL,
	C78_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C78_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C78_I1_REFUGO_ROMANEIO_CONTROLE_AMBIENTAL PRIMARY KEY (SCO_C78_REFUGO_ROMANEIO_CONTROLE_AMBIENTAL)
);


-- sco_desenv.dbo.SCO_C80_CORES definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C80_CORES;

CREATE TABLE sco_desenv.dbo.SCO_C80_CORES (
	C80_ID_COR int IDENTITY(1,1) NOT NULL,
	C80_CD_COR char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C80_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C80_DT_INCLUSAO datetime NOT NULL,
	C80_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C80_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C80_I1_CORES PRIMARY KEY (C80_ID_COR)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C80_I2_CORES ON dbo.SCO_C80_CORES (  C80_CD_COR ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE  UNIQUE NONCLUSTERED INDEX C80_I3_CORES ON dbo.SCO_C80_CORES (  C80_TX_DESCRICAO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C81_DIAS_SEMANA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C81_DIAS_SEMANA;

CREATE TABLE sco_desenv.dbo.SCO_C81_DIAS_SEMANA (
	C81_ID_DIA_SEMANA tinyint NOT NULL,
	C81_NR_DIA_SEMANA tinyint NOT NULL,
	C81_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C81_I1_DIAS_SEMANA PRIMARY KEY (C81_ID_DIA_SEMANA)
);


-- sco_desenv.dbo.SCO_C82_TURMAS_LIMPEZA_TEAR definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C82_TURMAS_LIMPEZA_TEAR;

CREATE TABLE sco_desenv.dbo.SCO_C82_TURMAS_LIMPEZA_TEAR (
	C82_ID_TURMA_LIMPEZA_TEAR int IDENTITY(1,1) NOT NULL,
	C82_TX_DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C82_DT_INCLUSAO datetime NOT NULL,
	C82_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C82_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C82_ID_TURMA_LIMPEZA_TEAR PRIMARY KEY (C82_ID_TURMA_LIMPEZA_TEAR)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C82_I2_TURMAS_LIMPEZA_TEAR ON dbo.SCO_C82_TURMAS_LIMPEZA_TEAR (  C82_TX_DESCRICAO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C83_CALENDARIO_LIMPEZA_TEAR definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C83_CALENDARIO_LIMPEZA_TEAR;

CREATE TABLE sco_desenv.dbo.SCO_C83_CALENDARIO_LIMPEZA_TEAR (
	C83_ID_CALENDARIO_LIMPEZA_TEAR int IDENTITY(1,1) NOT NULL,
	C82_ID_TURMA_LIMPEZA_TEAR int NOT NULL,
	C81_ID_DIA_SEMANA tinyint NOT NULL,
	C83_DT_INCLUSAO datetime NOT NULL,
	C83_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C83_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C83_I1_CALENDARIO_LIMPEZA_TEAR PRIMARY KEY (C83_ID_CALENDARIO_LIMPEZA_TEAR)
);
 CREATE  UNIQUE CLUSTERED INDEX C83_I2_CALENDARIO_LIMPEZA_TEAR ON dbo.SCO_C83_CALENDARIO_LIMPEZA_TEAR (  C82_ID_TURMA_LIMPEZA_TEAR ASC  , C81_ID_DIA_SEMANA ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_S65_IMPORTACAO_SALDO_ESTOQUE_INSUMO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_S65_IMPORTACAO_SALDO_ESTOQUE_INSUMO;

CREATE TABLE sco_desenv.dbo.SCO_S65_IMPORTACAO_SALDO_ESTOQUE_INSUMO (
	S65_ID_IMPORTACAO_SALDO_ESTOQUE_INSUMO int IDENTITY(1,1) NOT NULL,
	S65_DT_IMPORTACAO smalldatetime NOT NULL,
	S02_CD_USUARIO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	S65_TX_NOME_PLANILHA_ABA varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	S65_TX_NOME_ARQUIVO varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT S60_I1_IMPORTACAO_SALDO_ESTOQUE_INSUMO PRIMARY KEY (S65_ID_IMPORTACAO_SALDO_ESTOQUE_INSUMO)
);


-- sco_desenv.dbo.SCO_S66_SALDO_ESTOQUE_INSUMO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_S66_SALDO_ESTOQUE_INSUMO;

CREATE TABLE sco_desenv.dbo.SCO_S66_SALDO_ESTOQUE_INSUMO (
	S66_ID_SALDO_ESTOQUE_INSUMO int IDENTITY(1,1) NOT NULL,
	S65_ID_IMPORTACAO_SALDO_ESTOQUE_INSUMO int NOT NULL,
	L03_CD_MATERIAL char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C66_NR_QUANTIDADE_SALDO smallmoney NOT NULL,
	C66_NR_ESTOQUE_PULMAO smallmoney NOT NULL,
	C66_DT_INCLUSAO datetime NOT NULL,
	C66_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT S66_I1_SALDO_ESTOQUE_INSUMO PRIMARY KEY (S66_ID_SALDO_ESTOQUE_INSUMO)
);
 CREATE  UNIQUE CLUSTERED INDEX S66_I2_SALDO_ESTOQUE_INSUMO ON dbo.SCO_S66_SALDO_ESTOQUE_INSUMO (  S65_ID_IMPORTACAO_SALDO_ESTOQUE_INSUMO ASC  , L03_CD_MATERIAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SEN_S08_PERFIS definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SEN_S08_PERFIS;

CREATE TABLE sco_desenv.dbo.SEN_S08_PERFIS (
	S08_ID_PERFIL int NOT NULL,
	S08_CD_PERFIL varchar(13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	S01_CD_SISTEMA char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	S08_TM_ULT_ATUALIZACAO smalldatetime NULL,
	S08_ST_ATIVO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	S08_TX_DESCRICAO varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);
 CREATE  UNIQUE CLUSTERED INDEX S08_I1_PERFIS ON dbo.SEN_S08_PERFIS (  S08_ID_PERFIL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.sysdiagrams definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.sysdiagrams;

CREATE TABLE sco_desenv.dbo.sysdiagrams (
	name sysname COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	principal_id int NOT NULL,
	diagram_id int IDENTITY(1,1) NOT NULL,
	version int NULL,
	definition varbinary(MAX) NULL,
	CONSTRAINT PK__sysdiagr__C2B05B61BB9943C7 PRIMARY KEY (diagram_id),
	CONSTRAINT UK_principal_name UNIQUE (principal_id,name)
);


-- sco_desenv.dbo.SCO_C06_TEARES definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C06_TEARES;

CREATE TABLE sco_desenv.dbo.SCO_C06_TEARES (
	C06_ID_TEAR int IDENTITY(1,1) NOT NULL,
	C06_NR_TEAR char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C06_NR_TAMANHO_DIAMETRO int NOT NULL,
	C06_NR_ANO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C02_ID_TIPO_TEAR int NOT NULL,
	C04_ID_TIPO_APARELHO tinyint NOT NULL,
	C09_ID_CORREDOR smallint NOT NULL,
	C11_ID_LADO_CORREDOR smallint NOT NULL,
	C06_ST_APARELHO_DINEMA tinyint NOT NULL,
	C06_DT_INCLUSAO datetime NULL,
	C06_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C06_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C06_NR_PATRIMONIO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C82_ID_TURMA_LIMPEZA_TEAR int NULL,
	C06_NR_SERIE varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT C06_I1_TEARES PRIMARY KEY (C06_ID_TEAR),
	CONSTRAINT C06_C01_C04 FOREIGN KEY (C04_ID_TIPO_APARELHO) REFERENCES sco_desenv.dbo.SCO_C04_TIPOS_APARELHO(C04_ID_TIPO_APARELHO),
	CONSTRAINT C06_C01_C11 FOREIGN KEY (C11_ID_LADO_CORREDOR) REFERENCES sco_desenv.dbo.SCO_C11_LADOS_CORREDOR(C11_ID_LADO_CORREDOR),
	CONSTRAINT C06_C02_C02 FOREIGN KEY (C02_ID_TIPO_TEAR) REFERENCES sco_desenv.dbo.SCO_C02_TIPOS_TEAR(C02_ID_TIPO_TEAR)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C06_I2_TEARES ON dbo.SCO_C06_TEARES (  C06_NR_TEAR ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C07_TIPOS_PROGRAMA_TEAR definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C07_TIPOS_PROGRAMA_TEAR;

CREATE TABLE sco_desenv.dbo.SCO_C07_TIPOS_PROGRAMA_TEAR (
	C07_ID_TIPO_PROGRAMA_TEAR int IDENTITY(1,1) NOT NULL,
	C06_ID_TEAR int NOT NULL,
	C03_ID_TIPO_PROGRAMA int NOT NULL,
	C07_DT_INCLUSAO datetime NULL,
	C07_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C07_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C07_I1_TIPOS_PROGRAMA_TEAR PRIMARY KEY (C07_ID_TIPO_PROGRAMA_TEAR),
	CONSTRAINT C07_C01_C03 FOREIGN KEY (C03_ID_TIPO_PROGRAMA) REFERENCES sco_desenv.dbo.SCO_C03_TIPOS_PROGRAMA(C03_ID_TIPO_PROGRAMA)
);


-- sco_desenv.dbo.SCO_C21_FICHA_TECELAGEM definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C21_FICHA_TECELAGEM;

CREATE TABLE sco_desenv.dbo.SCO_C21_FICHA_TECELAGEM (
	C21_ID_FICHA_TECELAGEM int IDENTITY(1,1) NOT NULL,
	C20_ID_FICHA int NOT NULL,
	C21_CD_INTERNO varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	A17_CD_MODELO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	A18_NR_INDICE_TAM tinyint NULL,
	A17_SG_TAMANHO char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C15_ID_TIPO_MONTAGEM_CODIGO_INTERNO tinyint NOT NULL,
	C21_TX_COMPLEMENTO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C80_ID_COR int NULL,
	C21_NR_TAMANHO_DIAMETRO smallint NULL,
	C21_NR_PESO_GRAMAS decimal(6,2) NULL,
	C21_NR_PECAS_LOTE int NULL,
	C21_TX_LFA_REFERENCIA char(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C21_ST_SOLDA tinyint NULL,
	C12_ID_FLUXO_FABRICACAO tinyint NULL,
	C21_ST_DESENVOLVIMENTO tinyint NULL,
	C35_ID_DESCARTE tinyint NOT NULL,
	C05_ID_FAMILIA_PRODUTO smallint NULL,
	C21_NR_LOTES_CAIXA int NULL,
	C21_DT_INCLUSAO datetime NULL,
	C21_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C21_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C21_I1_FICHA_TECELAGEM PRIMARY KEY (C21_ID_FICHA_TECELAGEM),
	CONSTRAINT C21_C01_C20 FOREIGN KEY (C20_ID_FICHA) REFERENCES sco_desenv.dbo.SCO_C20_FICHAS(C20_ID_FICHA),
	CONSTRAINT C21_C02_C15 FOREIGN KEY (C15_ID_TIPO_MONTAGEM_CODIGO_INTERNO) REFERENCES sco_desenv.dbo.SCO_C15_TIPOS_MONTAGEM_CODIGO_INTERNO(C15_ID_TIPO_MONTAGEM_CODIGO_INTERNO),
	CONSTRAINT C21_C03_C80 FOREIGN KEY (C80_ID_COR) REFERENCES sco_desenv.dbo.SCO_C80_CORES(C80_ID_COR),
	CONSTRAINT C21_C04_C12 FOREIGN KEY (C12_ID_FLUXO_FABRICACAO) REFERENCES sco_desenv.dbo.SCO_C12_FLUXOS_FABRICACAO(C12_ID_FLUXO_FABRICACAO),
	CONSTRAINT C21_C05_C35 FOREIGN KEY (C35_ID_DESCARTE) REFERENCES sco_desenv.dbo.SCO_C35_DESCARTE(C35_ID_DESCARTE),
	CONSTRAINT C21_C06_C05 FOREIGN KEY (C05_ID_FAMILIA_PRODUTO) REFERENCES sco_desenv.dbo.SCO_C05_FAMILIA_PRODUTO(C05_ID_FAMILIA_PRODUTO)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C21_I2_FICHA_TECELAGEM ON dbo.SCO_C21_FICHA_TECELAGEM (  C20_ID_FICHA ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C22_INSUMOS_FICHA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C22_INSUMOS_FICHA;

CREATE TABLE sco_desenv.dbo.SCO_C22_INSUMOS_FICHA (
	C22_ID_INSUMO_FICHA int IDENTITY(1,1) NOT NULL,
	C20_ID_FICHA int NOT NULL,
	L03_CD_MATERIAL char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C22_NR_PERCENTUAL_CONSUMO decimal(5,2) NULL,
	C22_DT_INCLUSAO datetime NULL,
	C22_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C22_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C22_ST_TROCA_LOTE_FORNECEDOR tinyint NULL,
	CONSTRAINT C21_I1_TIPOS_TEAR_FICHA PRIMARY KEY (C22_ID_INSUMO_FICHA),
	CONSTRAINT C22_C01_C20 FOREIGN KEY (C20_ID_FICHA) REFERENCES sco_desenv.dbo.SCO_C20_FICHAS(C20_ID_FICHA)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C21_I2_TIPOS_TEAR_FICHA ON dbo.SCO_C22_INSUMOS_FICHA (  C20_ID_FICHA ASC  , L03_CD_MATERIAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C23_TENSAO_FICHA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C23_TENSAO_FICHA;

CREATE TABLE sco_desenv.dbo.SCO_C23_TENSAO_FICHA (
	C23_ID_TENSAO_FICHA int IDENTITY(1,1) NOT NULL,
	C20_ID_FICHA int NOT NULL,
	C08_ID_TIPO_TENSAO_KTF tinyint NULL,
	C23_NR_GRAMAS decimal(5,2) NULL,
	C23_DT_INCLUSAO datetime NULL,
	C23_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C23_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C23_I1_TENSAO_FICHA PRIMARY KEY (C23_ID_TENSAO_FICHA),
	CONSTRAINT C23_C01_C20 FOREIGN KEY (C20_ID_FICHA) REFERENCES sco_desenv.dbo.SCO_C20_FICHAS(C20_ID_FICHA),
	CONSTRAINT C23_C02_C08 FOREIGN KEY (C08_ID_TIPO_TENSAO_KTF) REFERENCES sco_desenv.dbo.SCO_C08_TIPOS_TENSAO_KTF(C08_ID_TIPO_TENSAO_KTF)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C23_I2_TENSAO_FICHA ON dbo.SCO_C23_TENSAO_FICHA (  C20_ID_FICHA ASC  , C08_ID_TIPO_TENSAO_KTF ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C24_TIPOS_TEAR_FICHA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C24_TIPOS_TEAR_FICHA;

CREATE TABLE sco_desenv.dbo.SCO_C24_TIPOS_TEAR_FICHA (
	C24_ID_TIPO_TEAR_FICHA int IDENTITY(1,1) NOT NULL,
	C20_ID_FICHA int NOT NULL,
	C02_ID_TIPO_TEAR int NULL,
	C03_ID_TIPO_PROGRAMA int NULL,
	C24_NR_CICLO_SEGUNDOS int NULL,
	C24_TX_NOME_PROGRAMA varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C24_TX_ENDERECO_PROGRAMA varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C24_ST_APARELHO_DINEMA tinyint NULL,
	C24_DT_INCLUSAO datetime NULL,
	C24_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C24_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C24_ID_TIPO_TEAR_FICHA_ORIGEM_COPIA int NULL,
	CONSTRAINT C24_I1_TIPOS_TEAR_FICHA PRIMARY KEY (C24_ID_TIPO_TEAR_FICHA),
	CONSTRAINT C24_C01_C20 FOREIGN KEY (C20_ID_FICHA) REFERENCES sco_desenv.dbo.SCO_C20_FICHAS(C20_ID_FICHA),
	CONSTRAINT C24_C02_C02 FOREIGN KEY (C02_ID_TIPO_TEAR) REFERENCES sco_desenv.dbo.SCO_C02_TIPOS_TEAR(C02_ID_TIPO_TEAR),
	CONSTRAINT C24_C03_C03 FOREIGN KEY (C03_ID_TIPO_PROGRAMA) REFERENCES sco_desenv.dbo.SCO_C03_TIPOS_PROGRAMA(C03_ID_TIPO_PROGRAMA)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C24_I2_TIPOS_TEAR_FICHA ON dbo.SCO_C24_TIPOS_TEAR_FICHA (  C20_ID_FICHA ASC  , C02_ID_TIPO_TEAR ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C25_MONTAGEM_FIOS_FICHA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C25_MONTAGEM_FIOS_FICHA;

CREATE TABLE sco_desenv.dbo.SCO_C25_MONTAGEM_FIOS_FICHA (
	C25_ID_MONTAGEM_FIOS_FICHA int IDENTITY(1,1) NOT NULL,
	C20_ID_FICHA int NOT NULL,
	C25_NR_CADUTA tinyint NOT NULL,
	C25_NR_GUIA_FIO tinyint NOT NULL,
	C22_ID_INSUMO_FICHA int NULL,
	C25_DT_INCLUSAO datetime NULL,
	S02_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C25_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C25_I1_MONTAGEM_FIOS_FICHA PRIMARY KEY (C25_ID_MONTAGEM_FIOS_FICHA),
	CONSTRAINT C25_C01_C20 FOREIGN KEY (C20_ID_FICHA) REFERENCES sco_desenv.dbo.SCO_C20_FICHAS(C20_ID_FICHA),
	CONSTRAINT C25_C02_C22 FOREIGN KEY (C22_ID_INSUMO_FICHA) REFERENCES sco_desenv.dbo.SCO_C22_INSUMOS_FICHA(C22_ID_INSUMO_FICHA)
);


-- sco_desenv.dbo.SCO_C26_MEDIDAS_FICHA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C26_MEDIDAS_FICHA;

CREATE TABLE sco_desenv.dbo.SCO_C26_MEDIDAS_FICHA (
	C26_ID_MEDIDAS_FICHA int IDENTITY(1,1) NOT NULL,
	C20_ID_FICHA int NOT NULL,
	C16_ID_MEDIDA tinyint NOT NULL,
	C17_ID_FORMATO tinyint NOT NULL,
	C26_VL_MEDIDA_MIN decimal(5,1) NULL,
	C26_VL_MEDIDA_MAX decimal(5,1) NULL,
	C26_DT_INCLUSAO datetime NULL,
	C26_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C26_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C26_I1_MEDIDAS_FICHA PRIMARY KEY (C26_ID_MEDIDAS_FICHA),
	CONSTRAINT C26_C01_C16 FOREIGN KEY (C16_ID_MEDIDA) REFERENCES sco_desenv.dbo.SCO_C16_MEDIDAS(C16_ID_MEDIDA),
	CONSTRAINT C26_C02_C17 FOREIGN KEY (C17_ID_FORMATO) REFERENCES sco_desenv.dbo.SCO_C17_FORMATOS(C17_ID_FORMATO),
	CONSTRAINT C26_C03_C20 FOREIGN KEY (C20_ID_FICHA) REFERENCES sco_desenv.dbo.SCO_C20_FICHAS(C20_ID_FICHA)
);


-- sco_desenv.dbo.SCO_C27_EVENTOS_FICHA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C27_EVENTOS_FICHA;

CREATE TABLE sco_desenv.dbo.SCO_C27_EVENTOS_FICHA (
	C27_ID_EVENTO_FICHA int IDENTITY(1,1) NOT NULL,
	C36_ID_EVENTO int NOT NULL,
	C20_ID_FICHA int NOT NULL,
	C19_ID_STATUS_FICHA int NOT NULL,
	C27_DT_EVENTO datetime NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C27_TX_OBSERVACAO varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT C27_I1_EVENTOS_FICHA PRIMARY KEY (C27_ID_EVENTO_FICHA),
	CONSTRAINT C27_C01_C36 FOREIGN KEY (C36_ID_EVENTO) REFERENCES sco_desenv.dbo.SCO_C36_EVENTOS(C36_ID_EVENTO),
	CONSTRAINT C27_C02_C20 FOREIGN KEY (C20_ID_FICHA) REFERENCES sco_desenv.dbo.SCO_C20_FICHAS(C20_ID_FICHA),
	CONSTRAINT C27_C03_C19 FOREIGN KEY (C19_ID_STATUS_FICHA) REFERENCES sco_desenv.dbo.SCO_C19_STATUS_FICHA(C19_ID_STATUS_FICHA)
);


-- sco_desenv.dbo.SCO_C28_TIPO_APARELHO_TIPO_TEAR_FICHA definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C28_TIPO_APARELHO_TIPO_TEAR_FICHA;

CREATE TABLE sco_desenv.dbo.SCO_C28_TIPO_APARELHO_TIPO_TEAR_FICHA (
	C28_ID_TIPO_APARELHO_TIPO_TEAR_FICHA int IDENTITY(1,1) NOT NULL,
	C24_ID_TIPO_TEAR_FICHA int NOT NULL,
	C04_ID_TIPO_APARELHO tinyint NOT NULL,
	C28_DT_INCLUSAO datetime NULL,
	C28_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C28_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C28_I1_TIPO_APARELHO_TIPO_TEAR_FICHA PRIMARY KEY (C28_ID_TIPO_APARELHO_TIPO_TEAR_FICHA),
	CONSTRAINT C28_C01_C24 FOREIGN KEY (C24_ID_TIPO_TEAR_FICHA) REFERENCES sco_desenv.dbo.SCO_C24_TIPOS_TEAR_FICHA(C24_ID_TIPO_TEAR_FICHA),
	CONSTRAINT C28_C02_C04 FOREIGN KEY (C04_ID_TIPO_APARELHO) REFERENCES sco_desenv.dbo.SCO_C04_TIPOS_APARELHO(C04_ID_TIPO_APARELHO)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C28_I2_TIPO_APARELHO_TIPO_TEAR_FICHA ON dbo.SCO_C28_TIPO_APARELHO_TIPO_TEAR_FICHA (  C24_ID_TIPO_TEAR_FICHA ASC  , C04_ID_TIPO_APARELHO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C31_PLANO_PRODUCAO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C31_PLANO_PRODUCAO;

CREATE TABLE sco_desenv.dbo.SCO_C31_PLANO_PRODUCAO (
	C31_ID_PLANO_PRODUCAO int IDENTITY(1,1) NOT NULL,
	C30_CD_SEMANA int NOT NULL,
	S02_CD_USUARIO_ACEITE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C31_DT_ACEITE datetime NULL,
	S02_CD_USUARIO_ACEITE_REVISAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C31_DT_ACEITE_REVISAO datetime NULL,
	C31_DT_EMISSAO_OF datetime NULL,
	C31_DT_IMPRESSAO_OF datetime NULL,
	C31_CD_USUARIO_IMPRESSAO_OF varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C31_DT_INCLUSAO datetime NULL,
	C31_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C31_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C31_I1_PLANO_PRODUCAO PRIMARY KEY (C31_ID_PLANO_PRODUCAO),
	CONSTRAINT C31_C01_C30 FOREIGN KEY (C30_CD_SEMANA) REFERENCES sco_desenv.dbo.SCO_C30_SEMANAS(C30_CD_SEMANA)
);


-- sco_desenv.dbo.SCO_C32_PRODUTOS_PLANO_PRODUCAO definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C32_PRODUTOS_PLANO_PRODUCAO;

CREATE TABLE sco_desenv.dbo.SCO_C32_PRODUTOS_PLANO_PRODUCAO (
	C32_ID_PRODUTO_PLANO_PRODUCAO int IDENTITY(1,1) NOT NULL,
	C31_ID_PLANO_PRODUCAO int NOT NULL,
	C20_CD_PRODUTO char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C32_NR_META_PECAS int NOT NULL,
	C32_DT_INCLUSAO datetime NULL,
	C32_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C32_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT C32_I1_PRODUTOS_PLANO_PRODUCAO PRIMARY KEY (C32_ID_PRODUTO_PLANO_PRODUCAO),
	CONSTRAINT C32_C01_C31 FOREIGN KEY (C31_ID_PLANO_PRODUCAO) REFERENCES sco_desenv.dbo.SCO_C31_PLANO_PRODUCAO(C31_ID_PLANO_PRODUCAO)
);


-- sco_desenv.dbo.SCO_C40_OF definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C40_OF;

CREATE TABLE sco_desenv.dbo.SCO_C40_OF (
	C40_ID_OF int IDENTITY(1,1) NOT NULL,
	C40_NR_OF int NOT NULL,
	C30_CD_SEMANA int NOT NULL,
	C37_ID_TIPO_OF tinyint NOT NULL,
	C20_ID_FICHA int NOT NULL,
	C06_ID_TEAR int NOT NULL,
	C40_DT_TROCA datetime NULL,
	C40_NR_QTDE_NECESSIDADE int NULL,
	C40_NR_QTDE_LOTES int NOT NULL,
	C40_NR_CODIGO_BARRAS int NULL,
	C39_ID_STATUS_OF tinyint NOT NULL,
	C40_DT_INICIO datetime NULL,
	P01_CD_EMPREGADO_INICIALIZACAO int NULL,
	C40_ST_INICIALIZACAO_MANUAL tinyint NULL,
	C40_DT_FIM datetime NULL,
	S02_CD_USUARIO_FINALIZACAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C40_ST_FINALIZACAO_MANUAL tinyint NULL,
	C40_DT_IMPRESSAO datetime NULL,
	S02_CD_USUARIO_IMPRESSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C40_ST_IMPRESSAO_MANUAL tinyint NULL,
	C40_DT_INCLUSAO datetime NULL,
	C40_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C40_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C40_TX_JUSTIFICATIVA varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT C40_I1_OFS PRIMARY KEY (C40_ID_OF),
	CONSTRAINT C40_C01_C37 FOREIGN KEY (C37_ID_TIPO_OF) REFERENCES sco_desenv.dbo.SCO_C37_TIPOS_OF(C37_ID_TIPO_OF),
	CONSTRAINT C40_C02_C39 FOREIGN KEY (C39_ID_STATUS_OF) REFERENCES sco_desenv.dbo.SCO_C39_STATUS_OF(C39_ID_STATUS_OF)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C40_I2_OFS ON dbo.SCO_C40_OF (  C40_NR_OF ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 80   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C41_LOTES definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C41_LOTES;

CREATE TABLE sco_desenv.dbo.SCO_C41_LOTES (
	C41_ID_LOTE int IDENTITY(1,1) NOT NULL,
	C40_ID_OF int NOT NULL,
	C41_NR_LOTE int NOT NULL,
	C41_NR_SEQUENCIAL int NOT NULL,
	C34_ID_TIPO_LOTE tinyint NOT NULL,
	C41_NR_QTDE_PECAS int NOT NULL,
	C41_NR_CODIGO_BARRAS int NULL,
	C41_DT_RECOLHIMENTO datetime NULL,
	C10_ID_TURNO smallint NULL,
	P01_CD_EMPREGADO int NULL,
	C38_ID_STATUS_LOTE tinyint NOT NULL,
	C41_DT_INCLUSAO datetime NULL,
	C41_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C41_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C41_DT_APROVACAO datetime NULL,
	C41_CD_USUARIO_APROVACAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C41_TX_JUSTIFICATIVA varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C46_ID_LOTE_ARTIGO int NULL,
	C71_ID_CAIXA int NULL,
	CONSTRAINT C41_I1_LOTES PRIMARY KEY (C41_ID_LOTE),
	CONSTRAINT C41_C01_C40 FOREIGN KEY (C40_ID_OF) REFERENCES sco_desenv.dbo.SCO_C40_OF(C40_ID_OF),
	CONSTRAINT C41_C02_C34 FOREIGN KEY (C34_ID_TIPO_LOTE) REFERENCES sco_desenv.dbo.SCO_C34_TIPOS_LOTE(C34_ID_TIPO_LOTE),
	CONSTRAINT C41_C03_C38 FOREIGN KEY (C38_ID_STATUS_LOTE) REFERENCES sco_desenv.dbo.SCO_C38_STATUS_LOTE(C38_ID_STATUS_LOTE),
	CONSTRAINT C41_C04_C46 FOREIGN KEY (C46_ID_LOTE_ARTIGO) REFERENCES sco_desenv.dbo.SCO_C46_LOTES_ARTIGO(C46_ID_LOTE_ARTIGO)
);


-- sco_desenv.dbo.SCO_C42_INSUMO_LOTES definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C42_INSUMO_LOTES;

CREATE TABLE sco_desenv.dbo.SCO_C42_INSUMO_LOTES (
	C42_ID_INSUMO_LOTE int IDENTITY(1,1) NOT NULL,
	C41_ID_LOTE int NOT NULL,
	L03_CD_MATERIAL char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C42_NR_CONSUMO smallmoney NULL,
	C42_DT_INCLUSAO datetime NULL,
	C42_CD_USUARIO_INCLUSAO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C42_DT_ULTIMA_ALTERACAO datetime NOT NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C47_ID_LOTE_INSUMO int NULL,
	CONSTRAINT C42_I1_INSUMO_LOTES PRIMARY KEY (C42_ID_INSUMO_LOTE),
	CONSTRAINT C42_C01_C41 FOREIGN KEY (C41_ID_LOTE) REFERENCES sco_desenv.dbo.SCO_C41_LOTES(C41_ID_LOTE),
	CONSTRAINT C42_C02_C47 FOREIGN KEY (C47_ID_LOTE_INSUMO) REFERENCES sco_desenv.dbo.SCO_C47_LOTES_INSUMO(C47_ID_LOTE_INSUMO)
);
 CREATE  UNIQUE NONCLUSTERED INDEX C42_I2_INSUMO_LOTES ON dbo.SCO_C42_INSUMO_LOTES (  C41_ID_LOTE ASC  , L03_CD_MATERIAL ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- sco_desenv.dbo.SCO_C43_EVENTOS_OF definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C43_EVENTOS_OF;

CREATE TABLE sco_desenv.dbo.SCO_C43_EVENTOS_OF (
	C43_ID_EVENTO_OF int IDENTITY(1,1) NOT NULL,
	C36_ID_EVENTO int NOT NULL,
	C40_ID_OF int NOT NULL,
	C39_ID_STATUS_OF tinyint NOT NULL,
	C43_DT_EVENTO datetime NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C43_TX_OBSERVACAO varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT C43_I1_EVENTOS_OF PRIMARY KEY (C43_ID_EVENTO_OF),
	CONSTRAINT C43_C01_C36 FOREIGN KEY (C36_ID_EVENTO) REFERENCES sco_desenv.dbo.SCO_C36_EVENTOS(C36_ID_EVENTO),
	CONSTRAINT C43_C02_C40 FOREIGN KEY (C40_ID_OF) REFERENCES sco_desenv.dbo.SCO_C40_OF(C40_ID_OF),
	CONSTRAINT C43_C03_C39 FOREIGN KEY (C39_ID_STATUS_OF) REFERENCES sco_desenv.dbo.SCO_C39_STATUS_OF(C39_ID_STATUS_OF)
);


-- sco_desenv.dbo.SCO_C44_EVENTOS_LOTE definição

-- Drop table

-- DROP TABLE sco_desenv.dbo.SCO_C44_EVENTOS_LOTE;

CREATE TABLE sco_desenv.dbo.SCO_C44_EVENTOS_LOTE (
	C44_ID_EVENTO_LOTE int IDENTITY(1,1) NOT NULL,
	C36_ID_EVENTO int NOT NULL,
	C41_ID_LOTE int NOT NULL,
	C38_ID_STATUS_LOTE tinyint NOT NULL,
	C44_DT_EVENTO datetime NULL,
	S02_CD_USUARIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C44_TX_OBSERVACAO varchar(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT C44_I1_EVENTOS_LOTE PRIMARY KEY (C44_ID_EVENTO_LOTE),
	CONSTRAINT C44_C01_C36 FOREIGN KEY (C36_ID_EVENTO) REFERENCES sco_desenv.dbo.SCO_C36_EVENTOS(C36_ID_EVENTO),
	CONSTRAINT C44_C02_C41 FOREIGN KEY (C41_ID_LOTE) REFERENCES sco_desenv.dbo.SCO_C41_LOTES(C41_ID_LOTE),
	CONSTRAINT C44_C03_C38 FOREIGN KEY (C38_ID_STATUS_LOTE) REFERENCES sco_desenv.dbo.SCO_C38_STATUS_LOTE(C38_ID_STATUS_LOTE)
);


-- dbo.SCO_V01_INSUMOS fonte

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW [dbo].[SCO_V01_INSUMOS]
AS
SELECT
	M15.L03_CD_MATERIAL AS L03_CD_MATERIAL,
	L03_TX_DESCRICAO,
	M18.M14_NR_GRUPO AS M14_NR_GRUPO,
	L11_CD_MESTRE,
	L03_IN_MESTRE_GRUPO
FROM materiais..[MAT_M15_MATERIAIS] M15
INNER JOIN materiais..MAT_M18_MATERIAIS_GRUPOS M18
ON M15.L03_CD_MATERIAL = M18.L03_CD_MATERIAL
LEFT JOIN materiais..MAT_M17_MESTRES_GRUPO M17
ON M17.L03_CD_MATERIAL = M15.L03_CD_MATERIAL
-- grupos: 
--   7 - FIOS COMPRADOS
-- 300 - MESTRE DE GRUPO DE FIOS
--  13 - PRODUCAO DO SETOR DE PREPARACAO TEXTIL
where M14_NR_GRUPO = 7 
OR M14_NR_GRUPO = 300 
OR M14_NR_GRUPO = 13;


-- dbo.SCO_V03_MESTRES_GRUPO fonte

CREATE VIEW [dbo].SCO_V03_MESTRES_GRUPO
AS
SELECT [L03_CD_MATERIAL]
      ,[L11_NR_PRIORIDADE]
      ,[L11_CD_MESTRE]
      ,[M17_VL_FATOR]
  FROM materiais..[MAT_M17_MESTRES_GRUPO];


-- dbo.SCO_V04_CONSUMO_LOTES_PENDENTES fonte

CREATE VIEW dbo.SCO_V04_CONSUMO_LOTES_PENDENTES
AS

	SELECT C50.C50_ID_ESTOQUE_INSUMO	AS ID_ESTOQUE_INSUMO 
		,C50.L03_CD_MATERIAL			AS CD_MATERIAL
		,V01_MATERIAL.L03_TX_DESCRICAO	AS TX_MATERIAL
		,C50.L11_CD_MESTRE				AS CD_MESTRE
		,V01_MESTRE.L03_TX_DESCRICAO	AS TX_MESTRE
		,C50.C50_NR_QUANTIDADE			AS NR_QUANTIDADE
		,C50.C50_NR_QUANTIDADE_PULMAO	AS NR_QUANTIDADE_PULMAO
		,SUM(C42.C42_NR_CONSUMO)		AS NR_CONSUMO
		,0								AS NR_CONES -- TODO: COLOCAR COLUNA DE CONES
	FROM dbo.SCO_C50_ESTOQUE_INSUMO C50
	INNER JOIN SCO_C42_INSUMO_LOTES C42
		ON C42.L03_CD_MATERIAL = C50.L03_CD_MATERIAL
	INNER JOIN SCO_C41_LOTES C41
		ON C41.C41_ID_LOTE = C42.C41_ID_LOTE
		AND C41.C38_ID_STATUS_LOTE = 1 -- STATUS LOTE ABERTO
	LEFT JOIN SCO_V01_INSUMOS V01_MATERIAL
		ON V01_MATERIAL.L03_CD_MATERIAL = C50.L03_CD_MATERIAL
	LEFT JOIN SCO_V01_INSUMOS V01_MESTRE
		ON V01_MESTRE.L11_CD_MESTRE = C50.L11_CD_MESTRE
	GROUP BY C50.C50_ID_ESTOQUE_INSUMO, C50.L03_CD_MATERIAL, C50.L11_CD_MESTRE, C50.C50_NR_QUANTIDADE, C50.C50_NR_QUANTIDADE_PULMAO, V01_MATERIAL.L03_TX_DESCRICAO, V01_MESTRE.L03_TX_DESCRICAO

	UNION ALL

	SELECT C50.C50_ID_ESTOQUE_INSUMO	AS ID_ESTOQUE_INSUMO 
		,C50.L03_CD_MATERIAL			AS CD_MATERIAL
		,V01_MATERIAL.L03_TX_DESCRICAO	AS TX_MATERIAL
		,C50.L11_CD_MESTRE				AS CD_MESTRE
		,V01_MESTRE.L03_TX_DESCRICAO	AS TX_MESTRE
		,C50.C50_NR_QUANTIDADE			AS NR_QUANTIDADE
		,C50.C50_NR_QUANTIDADE_PULMAO	AS NR_QUANTIDADE_PULMAO
		,SUM(C42.C42_NR_CONSUMO)		AS NR_CONSUMO
		,0								AS NR_CONES -- TODO: COLOCAR COLUNA DE CONES
	FROM dbo.SCO_C50_ESTOQUE_INSUMO C50
	INNER JOIN SCO_C42_INSUMO_LOTES C42
		ON C42.L03_CD_MATERIAL = C50.L11_CD_MESTRE
	INNER JOIN SCO_C41_LOTES C41
		ON C41.C41_ID_LOTE = C42.C41_ID_LOTE
		AND C41.C38_ID_STATUS_LOTE = 1 -- STATUS LOTE ABERTO
	LEFT JOIN SCO_V01_INSUMOS V01_MATERIAL
		ON V01_MATERIAL.L03_CD_MATERIAL = C50.L03_CD_MATERIAL
	LEFT JOIN SCO_V01_INSUMOS V01_MESTRE
		ON V01_MESTRE.L11_CD_MESTRE = C50.L11_CD_MESTRE
	GROUP BY C50.C50_ID_ESTOQUE_INSUMO, C50.L03_CD_MATERIAL, C50.L11_CD_MESTRE, C50.C50_NR_QUANTIDADE, C50.C50_NR_QUANTIDADE_PULMAO, V01_MATERIAL.L03_TX_DESCRICAO, V01_MESTRE.L03_TX_DESCRICAO;


-- dbo.SCO_V05_CONSUMO_LOTES_PENDENTES_POR_MESTRE fonte

CREATE VIEW [dbo].[SCO_V05_CONSUMO_LOTES_PENDENTES_POR_MESTRE]
AS

	SELECT SUM(NR_CONSUMO)	AS NR_CONSUMO
		,SUM(NR_CONES)		AS NR_CONES 
		,V04.CD_MESTRE		AS CD_MESTRE
	FROM SCO_V04_CONSUMO_LOTES_PENDENTES V04
	INNER JOIN SCO_V01_INSUMOS V01
		ON V01.L11_CD_MESTRE = V04.CD_MESTRE
	GROUP BY CD_MESTRE;


-- dbo.SCO_V06_TAMANHOS_MODELO fonte

-----------------------------------------------------------------------------------------------------
CREATE VIEW [dbo].[SCO_V06_TAMANHOS_MODELO]
AS
SELECT DISTINCT
    A20.A17_CD_MODELO AS A17_CD_MODELO,
    A20.A18_NR_INDICE_TAM AS A18_NR_INDICE_TAM,
    A20.A17_SG_TAMANHO AS A17_SG_TAMANHO,
	------------------------------------------------------------------------------------------------------------
	--ST_APLICA_OUTRO_TAMANHO
	--se o modelo tem tamanho numérico (por exemplo: 40, 42, ...)
	--seta flag "aplica outro tamanho". 
	--Significa que poderá ser informada outra sigla para montar o código interno
	--Por exemplo:
	--063551 tamanho 42, 44  
	--Código interno 63551A ==>o tamanho "A" será informado pelo usuário utilizado a opção "Outro" no combo de tamanho)
	------------------------------------------------------------------------------------------------------------
	CASE WHEN EXISTS(SELECT 1
						FROM empenho..EST_A20_ESTOQUE A20a            
						WHERE A20a.A17_CD_MODELO = A17.A17_CD_MODELO
						AND ISNUMERIC(A17_SG_TAMANHO) = 1) 
	THEN 1 
	ELSE 0 
	END 
	AS ST_APLICA_OUTRO_TAMANHO

FROM empenho..EST_A20_ESTOQUE A20            --EMPENHO
INNER JOIN empenho..A17_TP_MODELOS A17 ON 
A20.A17_CD_MODELO = A17.A17_CD_MODELO;


-- dbo.SCO_V07_HISTORICO_ALTERACOES_FICHA fonte

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW [dbo].[SCO_V07_HISTORICO_ALTERACOES_FICHA]
AS
SELECT
	C20.[C20_ID_FICHA],
	C20_VERSOES_ANTERIORES.C20_NR_VERSAO AS [C27_NR_VERSAO],
	C20_VERSOES_ANTERIORES.C20_DT_VERSAO AS [C27_DT_VERSAO],
	C20_VERSOES_ANTERIORES.C20_TX_JUSTIFICATIVA AS [C27_TX_JUSTIFICATIVA],
	C20_VERSOES_ANTERIORES. C20_CD_USUARIO_ELABORACAO AS [C27_TX_USUARIO_ELABORACAO] ,
	(SELECT S02_CD_USUARIO_APROVACAO 
	FROM SCO_C29_APROVACAO_FICHA
	WHERE C20_ID_FICHA = C20_VERSOES_ANTERIORES.C20_ID_FICHA
	AND [C29_NR_SEQUENCIA_APROVACAO] = 1) AS [C27_TX_USUARIO_APROVACAO_1],
	(SELECT S02_CD_USUARIO_APROVACAO 
	FROM SCO_C29_APROVACAO_FICHA
	WHERE C20_ID_FICHA = C20_VERSOES_ANTERIORES.C20_ID_FICHA
	AND [C29_NR_SEQUENCIA_APROVACAO] = 2) AS [C27_TX_USUARIO_APROVACAO_2],
	(SELECT S02_CD_USUARIO_APROVACAO 
	FROM SCO_C29_APROVACAO_FICHA
	WHERE C20_ID_FICHA = C20_VERSOES_ANTERIORES.C20_ID_FICHA
	AND [C29_NR_SEQUENCIA_APROVACAO] = 3) AS [C27_TX_USUARIO_APROVACAO_3]
FROM SCO_C20_FICHAS C20
INNER JOIN SCO_C20_FICHAS C20_VERSOES_ANTERIORES
ON C20.C20_CD_PRODUTO = C20_VERSOES_ANTERIORES.C20_CD_PRODUTO
--SOMENTE AS VERSÕES ANTERIORES
AND C20.C20_NR_VERSAO >= C20_VERSOES_ANTERIORES.C20_NR_VERSAO;


-- dbo.SCO_V08_EMPREGADOS fonte

CREATE VIEW [dbo].[SCO_V08_EMPREGADOS]
AS
SELECT
	[P09_CD_EMPRESA] ,
	[P01_CD_EMPREGADO],
	[P01_NR_SOLICIT_EMPREGADO],
	[P01_TX_NOME] ,
	5  AS C10_ID_TURNO   ---TODO: MUDAR
FROM DP..P01_PES_EMPREGADOS P01;


-- dbo.SCO_V17_MODELOS fonte

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW [dbo].[SCO_V17_MODELOS]
AS
	SELECT A17_CD_MODELO AS A17_CD_MODELO
		,A17_TX_DESCRICAO AS A17_TX_DESCRICAO
	FROM empenho..A17_TP_MODELOS A17
	--2		MEIA
	--11	SECRET
	--12	PROD.S/ESTOQUE COR M
	WHERE E03_CD_CLASSE_PRODUTO in (2, 11, 12);


-- dbo.SCO_V20_PRODUTOS_TECELAGEM fonte

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW [dbo].[SCO_V20_PRODUTOS_TECELAGEM]
AS
SELECT
	M15.L03_CD_MATERIAL AS L03_CD_MATERIAL,
	L03_TX_DESCRICAO AS L03_TX_DESCRICAO,
	L03_NR_DV AS L03_NR_DV, 
	M18.M14_NR_GRUPO AS M14_NR_GRUPO,
	L11_CD_MESTRE,
	L03_IN_MESTRE_GRUPO
FROM materiais..[MAT_M15_MATERIAIS] M15
INNER JOIN materiais..MAT_M18_MATERIAIS_GRUPOS M18
ON M15.L03_CD_MATERIAL = M18.L03_CD_MATERIAL
LEFT JOIN materiais..MAT_M17_MESTRES_GRUPO M17
ON M17.L03_CD_MATERIAL = M15.L03_CD_MATERIAL
-- grupos: 
--   70	PRODUCAO DA TECELAGEM DE MEIAS= DEMILLUS
--  116	CONFECCAO DEMILLUS= COSTURA= PECAS CRUAS
where (M14_NR_GRUPO = 70
OR M14_NR_GRUPO = 116)
AND L03_IN_MESTRE_GRUPO = 'N'   --> não pode ser mestre de grupo;


-- dbo.SCO_V22_INSUMOS_FICHA fonte

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW [dbo].[SCO_V22_INSUMOS_FICHA]
AS
SELECT 	[C22_ID_INSUMO_FICHA],
	[C20_ID_FICHA],
	[L03_CD_MATERIAL],
	[C22_NR_PERCENTUAL_CONSUMO],
	[C22_DT_INCLUSAO],
	[C22_CD_USUARIO_INCLUSAO],
	[C22_DT_ULTIMA_ALTERACAO],
	[S02_CD_USUARIO],
	(SELECT COUNT(C25_ID_MONTAGEM_FIOS_FICHA) 
        FROM SCO_C25_MONTAGEM_FIOS_FICHA C25
	WHERE C25.C22_ID_INSUMO_FICHA = C22.C22_ID_INSUMO_FICHA) AS NR_CONES
	FROM [SCO_C22_INSUMOS_FICHA] C22;


-- dbo.SEN_S02_USUARIOS fonte

create VIEW [dbo].[SEN_S02_USUARIOS]  
(  
 S02_CD_USUARIO  
 , S02_TX_SENHA  
 , S02_NM_USUARIO  
 , S02_TP_USUARIO  
 , S02_TX_EMAIL  
 , S02_DT_MODIFICACAO_SENHA  
 , P09_CD_EMPRESA  
 , P01_CD_EMPREGADO  
 , S02_IN_EMPREGADO_OU_FUNCAO  
 , S02_DT_VENCIMENTO_SENHA  
 , S02_ID_USUARIO  
 , S02_TX_TEL_RAMAL  
 , S02_CD_USER_VIVAZ  
 , S02_CD_USER_SOL  
 , S02_CD_USER_NEXO  
 , S02_CD_USER_SAPHIRA  
 , S02_CD_USER_TOTVS  
 , S12_CD_SETOR  
 , S13_NR_REG  
 , S02_CD_USER_WINT  
)  
AS  
 SELECT   
  S02_CD_USUARIO  
  , S02_TX_SENHA  
  , S02_NM_USUARIO  
  , S02_TP_USUARIO  
  , S02_TX_EMAIL  
  , S02_DT_MODIFICACAO_SENHA  
  , P09_CD_EMPRESA  
  , P01_CD_EMPREGADO  
  , S02_IN_EMPREGADO_OU_FUNCAO  
  , S02_DT_VENCIMENTO_SENHA  
  , S02_ID_USUARIO  
  , S02_TX_TEL_RAMAL  
  , S02_CD_USER_VIVAZ  
  , S02_CD_USER_SOL  
  , S02_CD_USER_NEXO  
  , S02_CD_USER_SAPHIRA  
  , S02_CD_USER_TOTVS  
  , S12_CD_SETOR  
  , S13_NR_REG  
  , S02_CD_USER_WINT  
   FROM controle.dbo.S02_SEN_USUARIOS;


-- dbo.SEN_S03_USUARIO_SISTEMAS fonte

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW [dbo].[SEN_S03_USUARIO_SISTEMAS]
(
	S02_CD_USUARIO
	, S01_CD_SISTEMA
	, S03_NR_MAX_LIGACOES
	, S03_NR_LIGACOES
	, S02_CD_PERFIL
	, S03_ID_USUARIO_SISTEMA
)
AS
SELECT
	S03.S02_CD_USUARIO
	, S03.S01_CD_SISTEMA
	, S03.S03_NR_MAX_LIGACOES
	, S03.S03_NR_LIGACOES
	, S03.S02_CD_PERFIL
	, S03.S03_ID_USUARIO_SISTEMA
FROM controle.dbo.S03_SEN_USUARIO_SISTEMAS S03;


-- dbo.SEN_V08_PERFIS fonte

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE VIEW [dbo].[SEN_V08_PERFIS]
(
	S08_CD_PERFIL 
)
AS
	SELECT DISTINCT S02_CD_PERFIL
	FROM CONTROLE..S03_SEN_USUARIO_SISTEMAS
	WHERE S01_CD_SISTEMA = 'SCO';