USE [portal_distribuicao]
GO
/****** Object:  StoredProcedure [dbo].[PDD_SP_BLOQUEIO_BUSCAR_LISTA]    Script Date: 07/11/2024 15:51:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

------------------------------------------------------------------------------------------
ALTER PROCEDURE [dbo].[PDD_SP_BLOQUEIO_BUSCAR_LISTA]
(
	 @nrPagina			INT
	, @nrLinhasPagina	INT
	, @nrTotalLinhas	INT OUTPUT
)
AS

DECLARE @nrLinhaInicial	INT
DECLARE @nrLinhaFinal	INT
DECLARE @numPaginas		INT

BEGIN

	CREATE TABLE #TMP_LISTA_BLOQUEIOS_PORTAL
	(
		NUM_LINHA				INT
		, ID_BLOQUEIO			INT
		, DT_INICIO				DATETIME
		, DT_FIM				DATETIME
		, TX_MOTIVO				VARCHAR(255)
		, NM_USUARIO_INCLUSAO	VARCHAR(12)
		, DT_INCLUSAO			DATETIME
		, NM_USUARIO_ALTERACAO	VARCHAR(12)
		, DT_ALTERACAO			DATETIME
	)

	INSERT INTO #TMP_LISTA_BLOQUEIOS_PORTAL
	(
		NUM_LINHA
		, ID_BLOQUEIO
		, DT_INICIO
		, DT_FIM
		, TX_MOTIVO
		, NM_USUARIO_INCLUSAO
		, DT_INCLUSAO
		, NM_USUARIO_ALTERACAO
		, DT_ALTERACAO
	)
	SELECT
		ROW_NUMBER() OVER ( ORDER BY P30.P30_DT_INICIO DESC )
		, P30.P30_ID_BLOQUEIO_PORTAL
		, P30.P30_DT_INICIO
		, P30.P30_DT_FIM
		, P30.P30_TX_MOTIVO
		, P30.P30_NM_USUARIO_INCLUSAO
		, P30.P30_DT_INCLUSAO
		, P30.P30_NM_USUARIO_ALTERACAO
		, P30.P30_DT_ALTERACAO
	FROM PDD_P30_BLOQUEIOS_PORTAL P30
	ORDER BY P30.P30_DT_INICIO DESC, P30.P30_DT_FIM DESC

	SELECT @nrTotalLinhas = COUNT( NUM_LINHA )
	FROM #TMP_LISTA_BLOQUEIOS_PORTAL

	SELECT @nrLinhaInicial = NR_LINHA_INICIAL, @nrLinhaFinal = NR_LINHA_FINAL
	FROM PDD_FN_DEFINE_LINHA_INICIAL_FINAL( @nrLinhasPagina, @nrPagina, @nrTotalLinhas )

	SELECT
		ID_BLOQUEIO
		, DT_INICIO
		, DT_FIM
		, TX_MOTIVO
		, NM_USUARIO_INCLUSAO
		, DT_INCLUSAO
		, NM_USUARIO_ALTERACAO
		, DT_ALTERACAO
	FROM #TMP_LISTA_BLOQUEIOS_PORTAL
	WHERE NUM_LINHA BETWEEN @nrLinhaInicial AND @nrLinhaFinal

END





ERRRADO, salvei por salvar

CREATE PROCEDURE [dbo].[PDD_SP_BLOQUEIO_AREA_LISTAR]
(
	@idBloqueio INT
)
AS
BEGIN
	SELECT
		  P30.P30_ID_BLOQUEIO_PORTAL	AS ID_BLOQUEIO
		, P30.P30_DT_INICIO				AS DT_INICIO
		, P30.P30_DT_FIM				AS DT_FIM
		, P30.P30_NM_USUARIO_INCLUSAO	AS NM_USUARIO_INCLUSAO
		, P30.P30_DT_INCLUSAO			AS DT_INCLUSAO
		, P30.P30_NM_USUARIO_ALTERACAO	AS NM_USUARIO_ALTERACAO
		, P30.P30_DT_ALTERACAO			AS DT_ALTERACAO
		, P30.P30_TX_MOTIVO				AS TX_MOTIVO
		, P30.P30_ID_AREA_MODULO_PORTAL AS ID_AREA_MODULO   
		, P33.P33_TX_AREA				AS TX_AREA     
		, P21.P21_TX_MODULO_PORTAL      AS TX_MODULO_PORTAL
	FROM PDD_P30_BLOQUEIOS_PORTAL P30
	INNER JOIN PDD_P34_AREAS_MODULOS P34
		ON P30.P30_ID_AREA_MODULO_PORTAL = P34.P34_ID_AREA_MODULO_PORTAL
	INNER JOIN PDD_P33_AREAS P33
		ON P33.P33_ID_AREA = P34.P33_ID_AREA
	INNER JOIN PDD_P21_MODULOS_PORTAL P21
		ON P21.P21_ID_MODULO_PORTAL = P34.P21_ID_MODULO_PORTAL
	WHERE P34_ST_PERMITE_BLOQUEIO = 1
END
