USE [portal_distribuicao]
GO

/****** Object:  StoredProcedure [dbo].[PDD_SP_BLOQUEIO_ALTERAR]    Script Date: 08/11/2024 10:16:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

------------------------------------------------------------------------------------------
ALTER PROCEDURE [dbo].[PDD_SP_BLOQUEIO_ALTERAR]
(
	@idBloqueio		INT
	, @dtInicio		DATE
	, @dtFim		DATE
	, @cdUsuario	VARCHAR(12)
	, @txMotivo		VARCHAR(255)
	, @idAreaModulo TINYINT
)
AS
BEGIN

	UPDATE PDD_P30_BLOQUEIOS_PORTAL
	SET
		P30_DT_INICIO = @dtInicio
		, P30_DT_FIM = @dtFim
		, P30_DT_ALTERACAO = GETDATE()
		, P30_NM_USUARIO_ALTERACAO = @cdUsuario
		, P30_TX_MOTIVO = @txMotivo
		, P30_ID_AREA_MODULO_PORTAL = @idAreaModulo
	WHERE P30_ID_BLOQUEIO_PORTAL = @idBloqueio

END

GO





/****** Object:  StoredProcedure [dbo].[PDD_SP_BLOQUEIO_ATIVO_LER]    Script Date: 08/11/2024 09:57:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

------------------------------------------------------------------------------------------
ALTER PROCEDURE [dbo].[PDD_SP_BLOQUEIO_ATIVO_LER]
AS
BEGIN

	SELECT
		P30_ID_BLOQUEIO_PORTAL		AS ID_BLOQUEIO
		, P30_DT_INICIO				AS DT_INICIO
		, P30_DT_FIM				AS DT_FIM
		, P30_NM_USUARIO_INCLUSAO	AS NM_USUARIO_INCLUSAO
		, P30_DT_INCLUSAO			AS DT_INCLUSAO
		, P30_NM_USUARIO_ALTERACAO	AS NM_USUARIO_ALTERACAO
		, P30_DT_ALTERACAO			AS DT_ALTERACAO
		, P30_TX_MOTIVO				AS TX_MOTIVO
		, P30_ID_AREA_MODULO_PORTAL AS ID_AREA_MODULO
		
	FROM PDD_P30_BLOQUEIOS_PORTAL
	WHERE P30_DT_INICIO <= CONVERT( DATE, GETDATE() )
	AND P30_DT_FIM >= CONVERT( DATE, GETDATE() )
	ORDER BY P30_DT_INICIO

END

GO






/****** Object:  StoredProcedure [dbo].[PDD_SP_BLOQUEIO_BUSCAR_LISTA]    Script Date: 07/11/2024 15:43:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

------------------------------------------------------------------------------------------
ALTER PROCEDURE [dbo].[PDD_SP_BLOQUEIO_BUSCAR_LISTA]
(
	 @nrPagina			INT
	, @nrLinhasPagina	INT
	, @nrTotalLinhas	INT OUTPUT
)
AS

DECLARE @nrLinhaInicial	INT
DECLARE @nrLinhaFinal	INT
DECLARE @numPaginas		INT

BEGIN

	CREATE TABLE #TMP_LISTA_BLOQUEIOS_PORTAL
	(
		NUM_LINHA				INT
		, ID_BLOQUEIO			INT
		, DT_INICIO				DATETIME
		, DT_FIM				DATETIME
		, TX_MOTIVO				VARCHAR(255)
		, NM_USUARIO_INCLUSAO	VARCHAR(12)
		, DT_INCLUSAO			DATETIME
		, NM_USUARIO_ALTERACAO	VARCHAR(12)
		, DT_ALTERACAO			DATETIME
		, ID_AREA_MODULO_PORTAL INT 
		, ID_AREA				INT
		, ID_MODULO				INT
		, TX_MODULO				VARCHAR(255)
		, TX_AREA				VARCHAR(255)
	)

	INSERT INTO #TMP_LISTA_BLOQUEIOS_PORTAL
	(
		NUM_LINHA
		, ID_BLOQUEIO
		, DT_INICIO
		, DT_FIM
		, TX_MOTIVO
		, NM_USUARIO_INCLUSAO
		, DT_INCLUSAO
		, NM_USUARIO_ALTERACAO
		, DT_ALTERACAO
		, ID_AREA_MODULO_PORTAL
		, ID_AREA
		, ID_MODULO
		, TX_MODULO
		, TX_AREA


	)
	SELECT
		ROW_NUMBER() OVER ( ORDER BY P30.P30_DT_INICIO DESC )
		, P30.P30_ID_BLOQUEIO_PORTAL
		, P30.P30_DT_INICIO
		, P30.P30_DT_FIM
		, P30.P30_TX_MOTIVO
		, P30.P30_NM_USUARIO_INCLUSAO
		, P30.P30_DT_INCLUSAO
		, P30.P30_NM_USUARIO_ALTERACAO
		, P30.P30_DT_ALTERACAO
		, P34.P34_ID_AREA_MODULO_PORTAL
		, P34.P33_ID_AREA
		, P34.P21_ID_MODULO_PORTAL
		, P21.P21_TX_MODULO_PORTAL
		, P33.P33_TX_AREA

	FROM PDD_P30_BLOQUEIOS_PORTAL P30
	INNER JOIN PDD_P34_AREAS_MODULOS P34
  ON P30.P30_ID_AREA_MODULO_PORTAL = P34.P34_ID_AREA_MODULO_PORTAL
  INNER JOIN PDD_P33_AREAS P33
  ON P33.P33_ID_AREA = P34.P33_ID_AREA
  INNER JOIN PDD_P21_MODULOS_PORTAL P21
  ON P34.P21_ID_MODULO_PORTAL = P21.P21_ID_MODULO_PORTAL

	ORDER BY P30.P30_DT_INICIO DESC, P30.P30_DT_FIM DESC

	SELECT @nrTotalLinhas = COUNT( NUM_LINHA )
	FROM #TMP_LISTA_BLOQUEIOS_PORTAL

	SELECT @nrLinhaInicial = NR_LINHA_INICIAL, @nrLinhaFinal = NR_LINHA_FINAL
	FROM PDD_FN_DEFINE_LINHA_INICIAL_FINAL( @nrLinhasPagina, @nrPagina, @nrTotalLinhas )

	SELECT
		ID_BLOQUEIO
		, DT_INICIO
		, DT_FIM
		, TX_MOTIVO
		, NM_USUARIO_INCLUSAO
		, DT_INCLUSAO
		, NM_USUARIO_ALTERACAO
		, DT_ALTERACAO
		, ID_AREA_MODULO_PORTAL
		, ID_AREA
		, ID_MODULO
		, TX_MODULO
		, TX_AREA

	FROM #TMP_LISTA_BLOQUEIOS_PORTAL
	WHERE NUM_LINHA BETWEEN @nrLinhaInicial AND @nrLinhaFinal

END








/****** Object:  StoredProcedure [dbo].[PDD_SP_BLOQUEIO_LER]    Script Date: 08/11/2024 10:24:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

------------------------------------------------------------------------------------------
ALTER PROCEDURE [dbo].[PDD_SP_BLOQUEIO_LER]
(
	@idBloqueio INT
)
AS
BEGIN

	SELECT
		P30_ID_BLOQUEIO_PORTAL		AS ID_BLOQUEIO
		, P30_DT_INICIO				AS DT_INICIO
		, P30_DT_FIM				AS DT_FIM
		, P30_NM_USUARIO_INCLUSAO	AS NM_USUARIO_INCLUSAO
		, P30_DT_INCLUSAO			AS DT_INCLUSAO
		, P30_NM_USUARIO_ALTERACAO	AS NM_USUARIO_ALTERACAO
		, P30_DT_ALTERACAO			AS DT_ALTERACAO
		, P30_TX_MOTIVO				AS TX_MOTIVO
		, P30_ID_AREA_MODULO_PORTAL AS ID_AREA_MODULO   
		, P34.P33_ID_AREA			AS ID_AREA
		, P34.P21_ID_MODULO_PORTAL  AS ID_MODULO
		, P33.P33_TX_AREA			AS TX_AREA
		, P21.P21_TX_MODULO_PORTAL  AS TX_MODULO
	
	FROM PDD_P30_BLOQUEIOS_PORTAL P30
		INNER JOIN PDD_P34_AREAS_MODULOS P34
			ON P30_ID_AREA_MODULO_PORTAL = P34_ID_AREA_MODULO_PORTAL
		INNER JOIN PDD_P33_AREAS P33
			ON P34.P33_ID_AREA = P33.P33_ID_AREA
		INNER JOIN PDD_P21_MODULOS_PORTAL P21
			ON P34.P21_ID_MODULO_PORTAL = P21.P21_ID_MODULO_PORTAL

	WHERE P30_ID_BLOQUEIO_PORTAL = @idBloqueio

END

GO

-- PDD_SP_BLOQUEIO_EXCLUIR NADA ALTERADO, SÓ SUA ID BLOQUEIO



/****** Object:  StoredProcedure [dbo].[PDD_SP_BLOQUEIO_INCLUIR]    Script Date: 08/11/2024 08:48:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

------------------------------------------------------------------------------------------
ALTER PROCEDURE [dbo].[PDD_SP_BLOQUEIO_INCLUIR]
(
	@dtInicio		DATE
	, @dtFim		DATE
	, @cdUsuario	VARCHAR(12)
	, @txMotivo		VARCHAR(255)
	, @idAreaModuloPortal TINYINT
)
AS
BEGIN

	INSERT INTO PDD_P30_BLOQUEIOS_PORTAL
	(
		P30_DT_INICIO
		, P30_DT_FIM
		, P30_DT_INCLUSAO
		, P30_NM_USUARIO_INCLUSAO
		, P30_DT_ALTERACAO
		, P30_NM_USUARIO_ALTERACAO
		, P30_TX_MOTIVO
		, P30_ID_AREA_MODULO_PORTAL
	)
	VALUES
	(
		@dtInicio
		, @dtFim
		, GETDATE()
		, @cdUsuario
		, NULL
		, NULL
		, @txMotivo
		, @idAreaModuloPortal
	)

END

GO






/****** Object:  StoredProcedure [dbo].[PDD_SP_BLOQUEIO_AREA_LISTAR]    Script Date: 06/11/2024 13:53:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


------------------------------------------------------------------------------------------
ALTER PROCEDURE [dbo].[PDD_SP_BLOQUEIO_LER]
(
	@idBloqueio INT
)
AS
BEGIN

	
	SELECT
		P30_ID_BLOQUEIO_PORTAL		AS ID_BLOQUEIO
		, P30_DT_INICIO				AS DT_INICIO
		, P30_DT_FIM				AS DT_FIM
		, P30_NM_USUARIO_INCLUSAO	AS NM_USUARIO_INCLUSAO
		, P30_DT_INCLUSAO			AS DT_INCLUSAO
		, P30_NM_USUARIO_ALTERACAO	AS NM_USUARIO_ALTERACAO
		, P30_DT_ALTERACAO			AS DT_ALTERACAO
		, P30_TX_MOTIVO				AS TX_MOTIVO
		, P30_ID_AREA_MODULO_PORTAL AS ID_AREA_MODULO   
		, P34.P33_ID_AREA			AS ID_AREA
		, P34.P21_ID_MODULO_PORTAL  AS ID_MODULO
		, P33.P33_TX_AREA			AS TX_AREA
		, P21.P21_TX_MODULO_PORTAL  AS TX_MODULO
	
	FROM PDD_P30_BLOQUEIOS_PORTAL P30
		INNER JOIN PDD_P34_AREAS_MODULOS P34
			ON P30_ID_AREA_MODULO_PORTAL = P34_ID_AREA_MODULO_PORTAL
		INNER JOIN PDD_P33_AREAS P33
			ON P34.P33_ID_AREA = P33.P33_ID_AREA
		INNER JOIN PDD_P21_MODULOS_PORTAL P21
			ON P34.P21_ID_MODULO_PORTAL = P21.P21_ID_MODULO_PORTAL

	WHERE P30_ID_BLOQUEIO_PORTAL = @idBloqueio	

END
GO



/****** Object:  StoredProcedure [dbo].[PDD_SP_BLOQUEIO_BUSCAR_LISTA]    Script Date: 08/11/2024 10:53:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

------------------------------------------------------------------------------------------
CREATE PROCEDURE [dbo].[PDD_SP_TIPOS_BLOQUEIO_BUSCAR_LISTA]

AS
BEGIN

SELECT P34_ID_AREA_MODULO_PORTAL		AS ID_AREA_MODULO
      ,P33.P33_ID_AREA					AS ID_AREA
      ,P34.P21_ID_MODULO_PORTAL			AS ID_MODULO
	  ,P34.P34_ST_PERMITE_BLOQUEIO		AS ST_PERMITE_BLOQUEIO
	  ,P33.P33_TX_AREA					AS TX_AREA
	  ,P21.P21_TX_MODULO_PORTAL			AS TX_MODULO
  FROM PDD_P34_AREAS_MODULOS P34
  INNER JOIN PDD_P33_AREAS P33
  ON P33.P33_ID_AREA = P34.P33_ID_AREA
  INNER JOIN PDD_P21_MODULOS_PORTAL P21
  ON P34.P21_ID_MODULO_PORTAL = P21.P21_ID_MODULO_PORTAL
  WHERE P34_ST_PERMITE_BLOQUEIO = 1
 
END
GO







--ALTER TABLE PDD_P34_AREAS_MODULOS
	--ADD P34_PERMITE_BLOQUEIO TINYINT NOT NULL DEFAULT 0

--UPDATE PDD_P34_AREAS_MODULOS
--SET P34_ST_PERMITE_BLOQUEIO = 1 
--WHERE P34_ID_AREA_MODULO_PORTAL IN (1, 2, 5, 8)