

/*
Resumo alterações
 
- Remoção do campo P42_ST_CD 
*/

-------------------------------------------------------------
-- CONSULTAS ALTERADAS  Remoção do campo P42_ST_CD -- ALTERADAS NO SQLQueriesModuloContainer
-------------------------------------------------------------

--[CONSULTA-1]-------------EMPRESA_CONFIGURACAO_ENVIO_LER----

SELECT
	P42.P42_ID_CONTAINER_EMPRESAS_CONFIGURACAO_ENVIO	AS ID_EMPRESA_CONFIGURACAO
	, M45.M38_CD_EMPRESA_COMPRAS					AS CD_EMPRESA_FATURAMENTO
	, CASE
		WHEN M45.M45_NM_APELIDO = '' THEN M45.M45_NM_RAZAO_SOCIAL
		ELSE M45.M45_NM_APELIDO
	END												AS NM_APELIDO	
  , P42.P42_VL_ESTIMADO_MAXIMO AS VL_ESTIMADO_MAXIMO
FROM {0}..MAT_M45_EMPRESAS_COMPRAS M45
LEFT JOIN PDD_P42_CONTAINER_EMPRESAS_CONFIGURACAO_ENVIO P42
	ON M45.M38_CD_EMPRESA_COMPRAS = P42.M38_CD_EMPRESA_COMPRAS
WHERE M45.M38_CD_EMPRESA_COMPRAS = @idEmpresa

--[CONSULTA-2]-------------EMPRESAS_CONFIGURACOES_BUSCAR_LISTA---

SELECT
	P42.P42_ID_CONTAINER_EMPRESAS_CONFIGURACAO_ENVIO	AS ID_EMPRESA_CONFIGURACAO
	, M45.M38_CD_EMPRESA_COMPRAS					AS CD_EMPRESA_FATURAMENTO
	, CASE
		WHEN M45.M45_NM_APELIDO = '' THEN M45.M45_NM_RAZAO_SOCIAL
		ELSE M45.M45_NM_APELIDO
	END												AS NM_APELIDO
  , P42.P42_VL_ESTIMADO_MAXIMO AS VL_ESTIMADO_MAXIMO
FROM {0}..MAT_M45_EMPRESAS_COMPRAS M45
LEFT JOIN PDD_P42_CONTAINER_EMPRESAS_CONFIGURACAO_ENVIO P42
	ON M45.M38_CD_EMPRESA_COMPRAS = P42.M38_CD_EMPRESA_COMPRAS
WHERE M45.N03_NR_ORIGEM IS NOT NULL



--[CONSULTA-3]---CONTAINER_EMPRESAS_ASSOCIADAS_USUARIO_BUSCAR_LISTA---

SELECT
	P43.M38_CD_EMPRESA_COMPRAS		AS CD_EMPRESA
	, CASE WHEN M45.M45_NM_APELIDO = ''
		THEN M45.M45_NM_RAZAO_SOCIAL
		ELSE M45.M45_NM_APELIDO
	END		AS NM_APELIDO
FROM PDD_P43_CONTAINER_USUARIOS_EMPRESA P43
INNER JOIN materiais..MAT_M45_EMPRESAS_COMPRAS M45
	ON M45.M38_CD_EMPRESA_COMPRAS = P43.M38_CD_EMPRESA_COMPRAS
INNER JOIN PDD_P42_CONTAINER_EMPRESAS_CONFIGURACAO_ENVIO P42
	ON P42.M38_CD_EMPRESA_COMPRAS = P43.M38_CD_EMPRESA_COMPRAS
WHERE P43.S02_CD_USUARIO = @cdUsuario
ORDER BY
	CASE WHEN M45.M45_NM_APELIDO = ''
		THEN M45.M45_NM_RAZAO_SOCIAL
		ELSE M45.M45_NM_APELIDO
	END


-------------------------------------------------------------
-- TABELA Remoção do campo P42_ST_CD 
-------------------------------------------------------------

--[TABELA-1]-------------------------------------------------
ALTER TABLE [dbo].[PDD_P42_CONTAINER_EMPRESAS_CONFIGURACAO_ENVIO]
	DROP COLUMN [P42_ST_CD]
GO
-------------------------------------------------------------


-------------------------------------------------------------
-- PROCEDURES Remoção do campo P42_ST_CD 
-------------------------------------------------------------

--[PROCEDURE-1]----------------------------------------------
ALTER PROCEDURE [dbo].[PDD_SP_CONTAINER_EMPRESA_CONFIGURACAO_ENVIO_ALTERAR]  
(  
 @idEmpresaConfiguracaoEnvio INT  
 , @idEmpresa    INT  
 , @cdUsuario    VARCHAR(8)  
 , @vlMaximo     MONEY  
)  
AS  
BEGIN  
  
 UPDATE PDD_P42_CONTAINER_EMPRESAS_CONFIGURACAO_ENVIO  
 SET  
   P42_DT_ULTIMA_ATUALIZACAO = GETDATE()  
  , S02_CD_USUARIO_ULTIMA_ATUALIZACAO = @cdUsuario  
  , P42_VL_ESTIMADO_MAXIMO = @vlMaximo  
 WHERE P42_ID_CONTAINER_EMPRESAS_CONFIGURACAO_ENVIO = @idEmpresaConfiguracaoEnvio  
  
END  
GO 

--[PROCEDURE-2]----------------------------------------------
ALTER PROCEDURE [dbo].[PDD_SP_CONTAINER_EMPRESA_CONFIGURACAO_ENVIO_INCLUIR]  
(  
 @idEmpresa  INT  
 , @cdUsuario VARCHAR(8)  
 , @vlMaximo  MONEY  
)  
AS  
BEGIN  
  
 INSERT INTO PDD_P42_CONTAINER_EMPRESAS_CONFIGURACAO_ENVIO  
 (  
  M38_CD_EMPRESA_COMPRAS  
  , P42_DT_CRIACAO  
  , S02_CD_USUARIO  
  , P42_DT_ULTIMA_ATUALIZACAO  
  , S02_CD_USUARIO_ULTIMA_ATUALIZACAO  
  , P42_VL_ESTIMADO_MAXIMO  
 )  
 VALUES  
 (  
  @idEmpresa  
  , GETDATE()  
  , @cdUsuario  
  , NULL  
  , NULL  
  , @vlMaximo  
 )  
  
END  
GO