use apn
go  
------------------------------------------------------------------------------------------  
CREATE PROCEDURE [dbo].[IDM_SP_CAIXA_BUSCAR_LISTA]  
(  
 @cdMaterial varchar(8)  
)  
AS  
BEGIN  
   
 DECLARE @ST_PECA AS varchar(1) = 'D'  
  
 select A15.A15_ID_ESTOQUE AS ID_ESTOQUE,  
  A15.A02_ID_ALMOX_PROCES AS ID_ALMOX_PROCES,  
  A14.L03_CD_MATERIAL  AS CD_MATERIAL,   
  VW13.L03_TX_DESCRICAO AS TX_MATERIAL,  
  A14.A14_ID_ROMANEIO  AS ID_ROMANEIO,   
  A14.A14_NR_ROMANEIO  AS NR_ROMANEIO,   
  A14.A14_DT_ENTRADA  AS DT_ENTRADA,  
  A04.A04_ID_LOCAL  AS ID_LOCAL,  
  A04.A04_CD_LOCAL  AS CD_LOCAL,  
  A04.A04_TX_DESCRICAO AS TX_LOCAL,    
  A15.A15_NR_CAIXA  AS NR_CAIXA,   
  A15.A15_NR_PESO_BRUTO AS NR_PESO_BRUTO,  
  A15.A15_NR_PESO_LIQUIDO AS NR_PESO_LIQUIDO,  
  A15.A15_NR_TARA   AS NR_TARA,    
  A15.A15_NR_QTDE   AS NR_QTDE,   
  A15.A15_NR_NUM_PECA  AS NR_NUM_PECA,  
  A12.A12_ID_EMBALAGEM AS ID_EMBALAGEM,   
  A12.A12_TX_DESCRICAO AS TX_EMBALAGEM,  
  A14.A14_NR_LOTE   AS NR_LOTE,   
  A14.A14_TX_OBSERVACOES AS TX_OBSERVACOES     
from APN_A14_ROMANEIOS A14  
inner join APN_A15_ESTOQUES A15  
on  A14.A14_ID_ROMANEIO = A15.A14_ID_ROMANEIO   
inner join APN_A04_LOCAIS A04  
on  A15.A04_ID_LOCAL = A04.A04_ID_LOCAL   
inner join APN_A13_MATERIAIS_PROCES_VIEW VW13  
on  A14.L03_CD_MATERIAL = VW13.L03_CD_MATERIAL   
and  A15.A02_ID_ALMOX_PROCES = VW13.A02_ID_ALMOX_PROCES   
inner join APN_A12_EMBALAGENS A12  
on  A14.A12_ID_EMBALAGEM = A12.A12_ID_EMBALAGEM  
where A15.A02_ID_ALMOX_PROCES in (3, 19)  
/*   
3 FIO COMPRADO  
19 FIO BENEFICIADO EXTERNO  
*/  
and  A14.L03_CD_MATERIAL = @cdMaterial  
and  A15.A19_ST_PECA =  @ST_PECA --constante caixa disponível  
order by A14_NR_ROMANEIO,A15_NR_CAIXA,A04_CD_LOCAL  
  
END  